In [5]:
import pandas as pd

data = {
    'Name': ['  vaheed     Khan', 'ARUN', 'sara '],
    'Email': ['vahHEed@gmail.com', 'arun@yahoo.com', 'sara@gmail.com'],
    'City': ['chennai', 'BANGALORE', 'kochi']
}

df = pd.DataFrame(data)
print(df)

                Name              Email       City
0    vaheed     Khan  vahHEed@gmail.com    chennai
1               ARUN     arun@yahoo.com  BANGALORE
2              sara      sara@gmail.com      kochi

In [6]:
df["Name"].str.strip().str.title()

#strip => used to remove the extra spaces
#strip will remove the extra space in the front and back
#title => Capitalize the first letter

0    Vaheed     Khan
1               Arun
2               Sara
Name: Name, dtype: object

In [7]:
df["Email"].str.lower()

0    vahheed@gmail.com
1       arun@yahoo.com
2       sara@gmail.com
Name: Email, dtype: object

In [8]:
df["Email"].str.upper()

0    VAHHEED@GMAIL.COM
1       ARUN@YAHOO.COM
2       SARA@GMAIL.COM
Name: Email, dtype: object

In [9]:
df["Email"].str.title()

0    Vahheed@Gmail.Com
1       Arun@Yahoo.Com
2       Sara@Gmail.Com
Name: Email, dtype: object

In [10]:
df["Email"]=df["Email"].str.lower()
df["Name"]=df["Name"].str.strip().str.title()
df["City"]=df["City"].str.lower()
df

              Name              Email       City
0  Vaheed     Khan  vahheed@gmail.com    chennai
1             Arun     arun@yahoo.com  bangalore
2             Sara     sara@gmail.com      kochi

In [11]:
df["Email"] .str.split("@")
#it is used to split the string by the delimiter

0    [vahheed, gmail.com]
1       [arun, yahoo.com]
2       [sara, gmail.com]
Name: Email, dtype: object

In [12]:
#add a new column create user name -> prefix of the mail id
#add a new column domain -> gmail

df["User_Name"] =df["Email"].str.split("@").str[0]
df["Domain"] =df["Email"].str.split("@").str[1]
df

              Name              Email       City User_Name     Domain
0  Vaheed     Khan  vahheed@gmail.com    chennai   vahheed  gmail.com
1             Arun     arun@yahoo.com  bangalore      arun  yahoo.com
2             Sara     sara@gmail.com      kochi      sara  gmail.com

In [13]:
df2 = df["Email"].str.split("@").str[1]
df["Domain"]=df2.str.split(".").str[0]
df

              Name              Email       City User_Name Domain
0  Vaheed     Khan  vahheed@gmail.com    chennai   vahheed  gmail
1             Arun     arun@yahoo.com  bangalore      arun  yahoo
2             Sara     sara@gmail.com      kochi      sara  gmail

In [43]:
import pandas as pd

data = {
    'Name': ['           vaheed     Khan                         ', 'ARUN', 'sara '],
    'Email': ['VaheeD@gmail.com', 'ARUN@yahoo.com', 'SARA@gmail.com'],
    'City': ['chennai', 'BANGALORE', 'kochi']
}

df = pd.DataFrame(data)
print(df)
df["User_name"]=df["Email"].str.title().str.split("@").str[0]
df2 = df["Email"].str.split("@").str[1]
df["Domain"]=df2.str.split(".").str[0]

                                                Name             Email  \
0             vaheed     Khan                    ...  VaheeD@gmail.com
1                                               ARUN    ARUN@yahoo.com
2                                              sara     SARA@gmail.com

        City
0    chennai
1  BANGALORE
2      kochi

In [44]:
df

,Name,Email,City,User_name,Domain
0,vaheed Khan ...,VaheeD@gmail.com,chennai,Vaheed,gmail
1,ARUN,ARUN@yahoo.com,BANGALORE,Arun,yahoo
2,sara,SARA@gmail.com,kochi,Sara,gmail

In [45]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "student_habits_performance.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "jayaantanaath/student-habits-vs-academic-performance",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipython-input-3256033762.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'student-habits-vs-academic-performance' dataset.
First 5 records:   student_id  age  gender  study_hours_per_day  social_media_hours  \
0      S1000   23  Female                  0.0                 1.2
1      S1001   20  Female                  6.9                 2.8
2      S1002   21    Male                  1.4                 3.1
3      S1003   23  Female                  1.0                 3.9
4      S1004   19  Female                  5.0                 4.4

   netflix_hours part_time_job  attendance_percentage  sleep_hours  \
0            1.1            No                   85.0          8.0
1            2.3            No                   97.3          4.6
2            1.3            No                   94.8          8.0
3            1.0            No                   71.0          9.2
4            0.5            No                   90.9          4.9

  diet_quality  exercise_frequency parental_education_level internet_quality  \
0         Fair                   6                   Master          Average
1         Good                   6              High School          Average
2         Poor                   1              High School             Poor
3         Poor                   4                   Master             Good
4         Fair                   3                   Master             Good

   mental_health_rating extracurricular_participation  exam_score
0                     8                           Yes        56.2
1                     8                            No       100.0
2                     1                            No        34.3
3                     1                           Yes        26.8
4                     1                            No        66.4

In [17]:
df

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [46]:
#to detect the null values
df.isnull().sum()

#count of null values in each and evry column

student_id                        0
age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64

In [47]:
df["parental_education_level"].unique()

array(['Master', 'High School', 'Bachelor', nan], dtype=object)

In [48]:
df["parental_education_level"]=df["parental_education_level"].fillna("Illiterate")

#fill all the values Null with "Illiterate"

In [49]:
#to check nullvalues
df.isnull().sum()

#count of null values in each and evry column

student_id                       0
age                              0
gender                           0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
exam_score                       0
dtype: int64

In [50]:
df.columns

Index(['student_id', 'age', 'gender', 'study_hours_per_day',
       'social_media_hours', 'netflix_hours', 'part_time_job',
       'attendance_percentage', 'sleep_hours', 'diet_quality',
       'exercise_frequency', 'parental_education_level', 'internet_quality',
       'mental_health_rating', 'extracurricular_participation', 'exam_score'],
      dtype='object')

In [51]:
#to drop the duplicates
len(df)

1000

In [52]:
len(df.drop_duplicates()) #it will drop the duplicates drop_duplicates

1000

Task 1

In [53]:
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [55]:
df["academic_lifestyle_index"]= (df["study_hours_per_day"]*3) + (df["attendance_percentage"]*0.4) - (df["social_media_hours"]*2) - (df["netflix_hours"]*1.5)
df1 = df[["student_id","academic_lifestyle_index","exam_score"]].sort_values("academic_lifestyle_index", ascending = False)
df1["rank"]=df1["academic_lifestyle_index"].rank(ascending=False)
df1.head()

    student_id  academic_lifestyle_index  exam_score  rank
253      S1253                     55.95        93.8   1.0
293      S1293                     55.04       100.0   2.0
131      S1131                     54.20       100.0   3.0
750      S1750                     53.24        98.5   4.0
606      S1606                     53.23        93.1   5.0

In [56]:
df1.describe()

       academic_lifestyle_index   exam_score         rank
count               1000.000000  1000.000000  1000.000000
mean                  36.562430    69.601500   500.500000
std                    6.476536    16.888564   288.819326
min                   15.840000    18.400000     1.000000
25%                   31.997500    58.475000   250.500000
50%                   36.470000    70.500000   500.500000
75%                   40.942500    81.325000   750.250000
max                   55.950000   100.000000  1000.000000

Statistics

In [25]:
#collecting,Analyzing,Interprting,Preseting the data

In [57]:
#Descriptive Statistics

#correlation
#mean - average
#median - sorting the data in ascending order (middle)
#mode - Highest frequency in the data

In [58]:
#correlation -> it is used to find the relationship between 2 numerical column

#icecream sales #temp

#correlation is of 3 time
#i) Postive correlation - direct  (temp - ice cream)

#ii) Negative Correlation - Indirect (temp - heater sales)

#iii) No correlation - no relation ship (temp - silver price)

#correlation => -1 to 1

#>0.5 - Strong Positive
#0.25 to 0.5 - weak positive

#-025 to 0.25 - no correlation

#<-0.5 - Negative Correlation
#-0.25 to -0.5 - weak Negative

df[["academic_lifestyle_index","exam_score"]].corr()

                          academic_lifestyle_index  exam_score
academic_lifestyle_index                  1.000000    0.716909
exam_score                                0.716909    1.000000

In [59]:
df[["academic_lifestyle_index","exam_score"]].corr().iloc[0,1]

np.float64(0.7169092820719385)

Task 2

In [60]:
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,academic_lifestyle_index
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2,29.95
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0,50.57
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3,33.97
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8,22.10
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4,41.81

In [61]:
df["healthy_student_flag"] = df["sleep_hours"].apply(lambda x : "Yes" if x>=7 else "No")
df1 = df.groupby("healthy_student_flag").agg(Avg_exam=("exam_score","mean")).reset_index()
df1

  healthy_student_flag   Avg_exam
0                   No  68.277405
1                  Yes  72.115362

In [33]:
round(df1.iloc[1,1] - df1.iloc[0,1],2)

np.float64(3.84)

In [34]:
print(f"The Student having sleep >=7 hours having higher scores compared to students with lesser sleep\n and the Average difference is {round(df1.iloc[1,1] - df1.iloc[0,1],2)} Marks")

The Student having sleep >=7 hours having higher scores compared to students with lesser sleep
 and the Average difference is 3.84 Marks

Phase 2 - Task 2

In [62]:
#strong positive
df["healthy_student"] = ((df["sleep_hours"] >= 7) & (df["exercise_frequency"] >= 3) & (df["diet_quality"]== "Good") | (df["diet_quality"]=="Excellent"))

df["healthy_student_flag"] = df["healthy_student"].map(lambda x : "Yes" if x == True else "No")

In [63]:
df["healthy_student"].unique()

array([False,  True])

In [64]:
df["healthy_student_flag"].unique()

array(['No', 'Yes'], dtype=object)

In [66]:
df1=df.groupby("healthy_student_flag").agg(Avg_exam = ("exam_score","mean")).reset_index()
df1

  healthy_student_flag   Avg_exam
0                   No  69.349618
1                  Yes  72.384337

Task 3

In [67]:
df["total_hours"]= df["netflix_hours"] + df["social_media_hours"]
df["digital_distraction_level"]= df["total_hours"].apply(lambda x: "High" if x >= 6 else "Moderate" if x >= 3 else "Low")
df[["digital_distraction_level","total_hours"]].head()

  digital_distraction_level  total_hours
0                       Low          2.3
1                  Moderate          5.1
2                  Moderate          4.4
3                  Moderate          4.9
4                  Moderate          4.9

In [68]:
df["digital_distraction_level"].unique()

array(['Low', 'Moderate', 'High'], dtype=object)

In [69]:
df[["study_hours_per_day","exam_score"]].describe()

       study_hours_per_day   exam_score
count           1000.00000  1000.000000
mean               3.55010    69.601500
std                1.46889    16.888564
min                0.00000    18.400000
25%                2.60000    58.475000
50%                3.50000    70.500000
75%                4.50000    81.325000
max                8.30000   100.000000

In [71]:
dfx = df.groupby("digital_distraction_level").agg(Avg_exam=("exam_score","mean"),Avg_study=("study_hours_per_day","mean")).reset_index().sort_values("Avg_exam")
dfx["Diff"] = dfx["Avg_exam"] - dfx["Avg_study"]
dfx.sort_values("Diff", ascending = False)

  digital_distraction_level   Avg_exam  Avg_study       Diff
1                       Low  76.529630   3.602646  72.926984
2                  Moderate  68.937216   3.548260  65.388956
0                      High  63.799333   3.492000  60.307333

Task 4

In [82]:
df = df[df["study_hours_per_day"]!=0]

In [83]:
df[["study_hours_per_day","exam_score"]].describe()

       study_hours_per_day  exam_score
count           987.000000  987.000000
mean              3.596859   69.980750
std               1.420468   16.620714
min               0.100000   18.400000
25%               2.600000   58.900000
50%               3.500000   70.600000
75%               4.500000   81.650000
max               8.300000  100.000000

In [84]:
df["study_score"] = df["exam_score"] / df["study_hours_per_day"]

In [85]:
df["study_score"].describe()

count    987.000000
mean      22.726490
std       19.656213
min       12.048193
25%       16.876643
50%       19.638889
75%       23.711712
max      534.000000
Name: study_score, dtype: float64

In [94]:
#> 20
#15 to 20
#<15

df["study_efficiency_level "]=df["study_score"].apply(lambda x : "High" if x > 20 else "Moderate" if x >=15 else "Low")

In [97]:
dfm = df.groupby("study_efficiency_level ").agg(Avg_exam_score=("exam_score","mean"), Avg_time_study=("study_hours_per_day","mean")).reset_index()
dfm

  study_efficiency_level   Avg_exam_score  Avg_time_study
0                    High       64.579193        2.593418
1                     Low       73.709000        5.277000
2                Moderate       75.200240        4.329087

In [99]:
dfm["score_per_hour"]= dfm["Avg_exam_score"]/dfm["Avg_time_study"]
dfm.sort_values("score_per_hour", ascending = False)

  study_efficiency_level   Avg_exam_score  Avg_time_study  score_per_hour
0                    High       64.579193        2.593418       24.901187
2                Moderate       75.200240        4.329087       17.370926
1                     Low       73.709000        5.277000       13.967974