In [ ]:
import pandas as pd

sheet_id = "1RVnUAGVsr4lrt7nZ2WOq2hFkj7gFcRef"
sheet_name = "Orders"  # or the visible tab name

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
df = pd.read_csv(url)

df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,01-21-2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,02-26-2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,02-26-2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,02-26-2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,05-04-2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

🏪 Sample Superstore – Business Case Study Questions 📌 Case Study 1: Loss Identification (Critical Business Problem)

The management wants to reduce losses.

Question: Identify which product categories and sub-categories are generating losses. Filter the data to find loss-making segments, rank them by total loss, and suggest which products should be discontinued or repriced.

In [ ]:
#l_df = filter profit < 0
#category wise - Total Loss (sum of loss) -> top 3
#sub-category wise - Total Loss (sum of loss) -> top 3
#segment wise - Total Loss (sum of loss) -> top 3


#product wise -> counts -> total loss

In [ ]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,01-21-2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,02-26-2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,02-26-2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,02-26-2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,05-04-2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
df["Category"].unique()

array(['Furniture', 'Office Supplies', 'Technology'], dtype=object)

In [ ]:
df["Sub-Category"].unique()

array(['Bookcases', 'Chairs', 'Labels', 'Tables', 'Storage',
       'Furnishings', 'Art', 'Phones', 'Binders', 'Appliances', 'Paper',
       'Accessories', 'Envelopes', 'Fasteners', 'Supplies', 'Machines',
       'Copiers'], dtype=object)

In [ ]:
df["Segment"].unique()

array(['Consumer', 'Corporate', 'Home Office'], dtype=object)

In [ ]:
df["Product Name"].unique()

array(['Bush Somerset Collection Bookcase',
       'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back',
       'Self-Adhesive Address Labels for Typewriters by Universal', ...,
       'Eureka Hand Vacuum, Bagless', 'LG G2',
       'Eldon Jumbo ProFile Portable File Boxes Graphite/Black'],
      dtype=object)

In [ ]:
def loss(x):
  if x < 0:
    return x
  else:
    return 0

df["loss"] = df["Profit"].apply(loss)
df1 = df.groupby("Category").agg(Total_loss = ("loss", "sum")).reset_index()
df1["rank"] = df1["Total_loss"].rank(ascending= True)
df1[["rank","Category","Total_loss"]]

   rank         Category  Total_loss
0   1.0        Furniture -60936.1090
1   2.0  Office Supplies -56615.2585
2   3.0       Technology -38579.9182

In [ ]:
df2 = df.groupby("Sub-Category").agg(Total_loss = ("loss", "sum")).reset_index()
df2["rank"] = df2["Total_loss"].rank(ascending= True)
df2.sort_values("Total_loss").head(3)

   Sub-Category  Total_loss  rank
3       Binders -38510.4964   1.0
16       Tables -32412.1483   2.0
11     Machines -30118.6682   3.0

In [ ]:
df[df["Category"] == "Furniture"].groupby("Sub-Category").agg(Total_loss = ("loss", "sum")).reset_index().sort_values("Total_loss", ascending= True)

  Sub-Category  Total_loss
3       Tables -32412.1483
0    Bookcases -12152.2060
1       Chairs  -9880.8413
2  Furnishings  -6490.9134

In [ ]:
df1 = df[(df["Category"] == "Office Supplies") ].groupby("Sub-Category").agg(Total_loss = ("loss", "sum")).reset_index().sort_values("Total_loss", ascending= True)
df1[df1["Total_loss"]<0]

  Sub-Category  Total_loss
2      Binders -38510.4964
0   Appliances  -8629.6412
7      Storage  -6426.3038
8     Supplies  -3015.6219
4    Fasteners    -33.1952

In [ ]:
df2 = df[(df["Category"] == "Technology") ].groupby("Sub-Category").agg(Total_loss = ("loss", "sum")).reset_index().sort_values("Total_loss", ascending= True)
df2[df2["Total_loss"]<0]

  Sub-Category  Total_loss
2     Machines -30118.6682
3       Phones  -7530.6235
0  Accessories   -930.6265

In [ ]:
df3 = df.groupby("Segment").agg(Total_loss = ("loss", "sum")).reset_index()
df3["rank"] = round(df3["Total_loss"].rank(ascending= True))
df3.sort_values("Total_loss").head(3)

       Segment  Total_loss  rank
0     Consumer -84945.7112   1.0
1    Corporate -44787.2076   2.0
2  Home Office -26398.3669   3.0

In [ ]:
df4 = df.groupby("Product Name").agg(Total_loss = ("loss", "sum")).reset_index()
df4["rank"] = round(df4["Total_loss"].rank(ascending= True))
df4.sort_values("Total_loss").head(3)

                                  Product Name  Total_loss  rank
475  Cubify CubeX 3D Printer Double Head Print  -9239.9692   1.0
683  GBC DocuBind P400 Electric Binding System  -6859.3896   2.0
985  Lexmark MX611dhe Monochrome Laser Printer  -5269.9690   3.0

In [ ]:
#for category : Furniture -> Tables need to discontinue or reprice.
#for category : Office Supplies -> Binders need to discontinue or reprice.
#for category : Technology -> Machines need to discontinue or reprice.
#The highest loss -> Binders -> -38510.4964

📌 Shipping & Delivery Optimization

Operations team wants to reduce logistics cost.

Question: Analyze shipping modes vs delivery time vs profit. Which shipping mode results in higher delays or lower profit, and how should the company optimize shipping strategy?

In [ ]:
#delivery_time = shipp_date - order_date

In [ ]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code      float64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
loss             float64
dtype: object

In [ ]:
df["Order Date"]=pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%d/%m/%Y")
df["Delivery_Time"] = df["Ship Date"] - df["Order Date"]
df1= df.groupby("Ship Mode").agg(Average_Delay = ("Delivery_Time","mean"),Average_profit = ("Profit","mean")).reset_index().sort_values("Average_Delay", ascending = False)
df1["Average_Delay"] = df1["Average_Delay"].dt.days
df1[(df1["Average_Delay"]>=3) | (df1["Average_profit"] < 28)]

        Ship Mode  Average_Delay  Average_profit
3  Standard Class              5       27.494770
2    Second Class              3       29.535545