In [ ]:
import pandas as pd

In [ ]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]

import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the file path (CSV inside the dataset)
file_path = "HRDataset_v14.csv"

# Load the latest version of the dataset
df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "rhuebner/human-resources-data-set",
    file_path
)

print("First 5 records:")
print(df.head())

/tmp/ipython-input-3647318895.py:11: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading from https://www.kaggle.com/api/v1/datasets/download/rhuebner/human-resources-data-set?dataset_version_number=4&file_name=HRDataset_v14.csv...

100%|██████████| 75.1k/75.1k [00:00<00:00, 1.29MB/s]

First 5 records:
              Employee_Name  EmpID  MarriedID  MaritalStatusID  GenderID  \
0       Adinolfi, Wilson  K  10026          0                0         1
1  Ait Sidi, Karthikeyan     10084          1                1         1
2         Akinkuolie, Sarah  10196          1                1         0
3              Alagbe,Trina  10088          1                1         0
4          Anderson, Carol   10069          0                2         0

   EmpStatusID  DeptID  PerfScoreID  FromDiversityJobFairID  Salary  ...  \
0            1       5            4                       0   62506  ...
1            5       3            3                       0  104437  ...
2            5       5            3                       0   64955  ...
3            1       5            3                       0   64991  ...
4            5       5            3                       0   50825  ...

      ManagerName  ManagerID RecruitmentSource PerformanceScore  \
0  Michael Albert       22.0          LinkedIn          Exceeds
1      Simon Roup        4.0            Indeed      Fully Meets
2  Kissy Sullivan       20.0          LinkedIn      Fully Meets
3    Elijiah Gray       16.0            Indeed      Fully Meets
4  Webster Butler       39.0     Google Search      Fully Meets

   EngagementSurvey EmpSatisfaction SpecialProjectsCount  \
0              4.60               5                    0
1              4.96               3                    6
2              3.02               3                    0
3              4.84               5                    0
4              5.00               4                    0

  LastPerformanceReview_Date DaysLateLast30 Absences
0                  1/17/2019              0        1
1                  2/24/2016              0       17
2                  5/15/2012              0        3
3                   1/3/2019              0       15
4                   2/1/2016              0        2

[5 rows x 36 columns]

In [ ]:
#power number
a = 145
#1! - 1
#4! - 4*3*2*1 = 24
#5! - 5*4*3*2*1 = 120

#1+24+120 = 145

In [ ]:
def sum_factorial(x,y,z):
  fx = 1
  for i in range(1,x+1):
    fx *= i
    fy =1
    for i in range(1,y+1):
      fy *= i
      fz = 1
      for i in range(1,z+1):
        fz *= i
  return fx+fy+fz

In [ ]:
sum_factorial(2,4,5)

146

In [ ]:
#pandas practice question (HR question)
#A.Filtering (Easy)

#Filter all employees who work in the sales department
df[df["Department"]=="Sales"]

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
32,"Bunbury, Jessica",10188,1,1,0,5,6,3,0,74326,...,John Smith,17.0,Google Search,Fully Meets,3.14,5,0,2/10/2013,1,19
40,"Carter, Michelle",10040,0,0,0,1,6,3,0,71860,...,John Smith,17.0,Indeed,Fully Meets,5.00,5,0,1/21/2019,0,7
45,"Chigurh, Anton",10200,0,0,1,1,6,3,0,66808,...,Lynn Daneault,21.0,Employee Referral,Fully Meets,3.00,5,0,1/19/2019,0,17
60,"Daneault, Lynn",10099,0,0,0,1,6,3,0,65729,...,Debra Houlihan,15.0,Indeed,Fully Meets,4.62,4,0,1/24/2019,0,8
67,"Delarge, Alex",10306,0,0,1,1,6,1,0,61568,...,John Smith,17.0,Indeed,PIP,1.93,3,0,1/30/2019,6,5
72,"Dietrich, Jenna",10304,0,0,0,1,6,1,0,59231,...,John Smith,17.0,Website,PIP,2.30,1,0,1/29/2019,2,17
77,"Driver, Elle",10006,0,0,0,1,6,4,0,74241,...,Lynn Daneault,21.0,Indeed,Exceeds,4.77,5,0,1/27/2019,0,14
95,"Forrest, Alex",10305,1,1,1,1,6,3,0,70187,...,Lynn Daneault,21.0,Employee Referral,PIP,2.00,5,0,1/28/2019,4,7
98,"Fraval, Maruk",10258,0,0,1,1,6,3,0,67251,...,Lynn Daneault,21.0,CareerBuilder,Fully Meets,4.30,3,0,1/27/2019,2,7
104,"Gill, Whitney",10142,0,4,0,4,6,3,0,59370,...,John Smith,17.0,CareerBuilder,Fully Meets,3.97,4,0,1/15/2014,0,7
107,"Givens, Myriam",10255,0,0,0,1,6,3,0,61555,...,Lynn Daneault,21.0,Indeed,Fully Meets,4.50,5,0,1/25/2019,0,20
121,"Guilianno, Mike",10109,0,0,1,5,6,3,0,71707,...,John Smith,17.0,LinkedIn,Fully Meets,4.50,5,0,2/1/2013,0,20
128,"Hitchcock, Alfred",10167,1,1,1,1,6,3,0,70545,...,John Smith,17.0,Indeed,Fully Meets,3.60,5,0,1/30/2019,0,9
131,"Houlihan, Debra",10272,1,1,0,1,6,3,0,180000,...,Janet King,2.0,LinkedIn,Fully Meets,4.50,4,0,1/21/2019,0,19
147,"Kampew, Donysha",10244,0,0,0,5,6,3,0,68999,...,Debra Houlihan,15.0,Google Search,Fully Meets,4.50,5,0,3/30/2013,0,2
149,"Khemmich, Bartholemew",10231,0,0,1,1,6,3,0,65310,...,Lynn Daneault,21.0,Indeed,Fully Meets,4.30,5,0,1/22/2019,0,13
155,"Kreuger, Freddy",10165,0,0,1,1,6,3,1,71339,...,John Smith,17.0,Diversity Job Fair,Fully Meets,3.65,5,0,1/17/2019,0,20
166,"Leruth, Giovanni",10103,0,3,1,1,6,3,0,70468,...,John Smith,17.0,Website,Fully Meets,4.53,3,0,1/29/2019,0,16
184,"McKinzie, Jac",10202,1,1,1,2,6,3,0,63291,...,Lynn Daneault,21.0,Website,Fully Meets,3.40,4,0,1/29/2019,0,7
202,"Nguyen, Dheepa",10042,0,0,0,1,6,3,0,63695,...,Lynn Daneault,21.0,Indeed,Fully Meets,5.00,5,0,1/25/2019,0,2
207,"Onque, Jasmine",10121,0,0,0,1,6,3,0,63051,...,Lynn Daneault,21.0,Indeed,Fully Meets,4.28,3,0,1/25/2019,0,1
210,"Ozark, Travis",10041,0,0,1,1,6,3,0,68829,...,John Smith,17.0,Website,Fully Meets,5.00,5,0,1/14/2019,0,18
223,"Potts, Xana",10124,1,1,0,1,6,3,0,61844,...,Lynn Daneault,21.0,Website,Fully Meets,4.20,5,0,2/1/2019,0,9
230,"Ren, Kylo",10140,1,1,1,1,6,3,0,61809,...,John Smith,17.0,CareerBuilder,Fully Meets,3.98,3,0,1/28/2019,0,4
258,"Smith, John",10291,0,2,1,1,6,2,1,72992,...,Debra Houlihan,15.0,Diversity Job Fair,Needs Improvement,2.40,4,0,1/16/2019,2,16
267,"Stansfield, Norman",10307,1,1,1,1,6,1,0,58273,...,Lynn Daneault,21.0,Website,PIP,1.81,2,0,1/17/2019,3,5
270,"Strong, Caitrin",10241,1,1,0,1,6,3,0,60120,...,John Smith,17.0,Indeed,Fully Meets,4.10,4,0,1/31/2019,0,18
278,"Terry, Sharlene",10161,0,0,0,1,6,3,0,58370,...,Lynn Daneault,21.0,Indeed,Fully Meets,3.69,3,0,1/28/2019,0,18
282,"Torrence, Jack",10013,0,3,1,1,6,4,0,64397,...,Lynn Daneault,21.0,Indeed,Exceeds,4.10,3,0,1/4/2019,0,6
288,"Valentin,Jackie",10205,1,1,0,1,6,3,0,57859,...,John Smith,17.0,Indeed,Fully Meets,2.81,3,0,1/17/2019,0,16
291,"Villanueva, Noah",10253,0,0,1,1,6,3,0,55875,...,John Smith,17.0,Website,Fully Meets,4.50,4,0,1/18/2019,0,11

In [ ]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Sex', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences'],
      dtype='object')

In [ ]:
# Get employees whose Salary > 60000
df[df["Salary"] > 60000]

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
6,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,"Winthrop, Jordan",10033,0,0,1,5,5,4,0,70507,...,Brannon Miller,12.0,LinkedIn,Exceeds,5.00,3,0,1/19/2016,0,7
305,"Wolk, Hang T",10174,0,0,0,1,5,3,0,60446,...,David Stanley,14.0,LinkedIn,Fully Meets,3.40,4,0,2/21/2019,0,14
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11

In [ ]:
# Find employees who are terminated (Termd == 1).
df[df["Termd"] == 1]

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
10,"Baczenski, Rachael",10252,1,1,0,5,5,3,1,54670,...,David Stanley,14.0,Diversity Job Fair,Fully Meets,4.20,4,0,1/30/2016,0,12
11,"Barbara, Thomas",10242,1,1,1,5,5,3,1,47211,...,Kissy Sullivan,20.0,Diversity Job Fair,Fully Meets,4.20,3,0,5/6/2016,0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,"Wilber, Barry",10048,1,1,1,5,5,3,0,55140,...,Amy Dunn,11.0,Website,Fully Meets,5.00,3,0,2/15/2015,0,7
302,"Wilkes, Annie",10204,0,2,0,5,5,3,0,58062,...,Ketsia Liebig,19.0,Google Search,Fully Meets,3.60,5,0,2/6/2011,0,9
303,"Williams, Jacquelyn",10264,0,0,0,5,5,3,1,59728,...,Ketsia Liebig,19.0,Diversity Job Fair,Fully Meets,4.30,4,0,6/2/2014,0,16
304,"Winthrop, Jordan",10033,0,0,1,5,5,4,0,70507,...,Brannon Miller,12.0,LinkedIn,Exceeds,5.00,3,0,1/19/2016,0,7
307,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4

In [ ]:
# List employees from the state of MA.
df[df["State"] == "MA"]

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
307,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

In [ ]:
#Filter employees with PerformanceScore = 'Exceeds'.
df[df["PerformanceScore"]=='Exceeds']

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
5,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
12,"Barbossa, Hector",10012,0,2,1,1,3,4,1,92328,...,Simon Roup,4.0,Diversity Job Fair,Exceeds,4.28,4,5,2/25/2019,0,9
16,"Beak, Kimberly",10023,1,1,0,2,5,4,0,70131,...,Kelley Spirea,18.0,Employee Referral,Exceeds,4.40,3,0,1/14/2019,0,16
22,"Billis, Helen",10003,1,1,0,1,5,4,0,62910,...,Brannon Miller,12.0,Indeed,Exceeds,5.00,3,0,2/27/2019,0,19
36,"Candie, Calvin",10001,0,0,1,1,5,4,0,72640,...,Janet King,2.0,Indeed,Exceeds,5.00,3,0,2/22/2019,0,14
51,"Clukey, Elijian",10029,1,1,1,2,5,4,0,50373,...,Brannon Miller,12.0,Employee Referral,Exceeds,4.10,4,0,2/28/2019,0,5
55,"Corleone, Vito",10019,0,0,1,1,5,4,0,170500,...,Janet King,2.0,Indeed,Exceeds,3.70,5,0,2/4/2019,0,15
76,"Dougall, Eric",10028,0,0,1,1,3,4,0,138888,...,Jennifer Zamora,5.0,Indeed,Exceeds,4.30,5,5,1/4/2019,0,4
77,"Driver, Elle",10006,0,0,0,1,6,4,0,74241,...,Lynn Daneault,21.0,Indeed,Exceeds,4.77,5,0,1/27/2019,0,14
96,"Foss, Jason",10015,0,0,1,1,3,4,0,178000,...,Jennifer Zamora,5.0,Indeed,Exceeds,5.00,5,5,1/7/2019,0,15
106,"Girifalco, Evelyn",10018,0,0,0,1,5,4,0,57815,...,Amy Dunn,11.0,Indeed,Exceeds,3.90,4,0,2/7/2019,0,3
111,"Gonzalez, Cayo",10031,0,2,1,1,5,4,1,59892,...,Brannon Miller,12.0,Diversity Job Fair,Exceeds,4.50,4,0,2/18/2019,0,1
125,"Harrison, Kara",10007,1,1,0,1,5,4,0,62065,...,Amy Dunn,11.0,CareerBuilder,Exceeds,4.76,4,0,2/15/2019,0,5
141,"Jeannite, Tayana",10009,0,2,0,1,5,4,0,60724,...,Ketsia Liebig,19.0,LinkedIn,Exceeds,4.60,4,0,2/25/2019,0,11
143,"Johnson, George",10034,1,1,1,5,5,4,0,46837,...,Michael Albert,22.0,CareerBuilder,Exceeds,4.70,4,0,2/14/2018,0,9
145,"Johnston, Yen",10036,0,0,0,1,5,4,0,63322,...,Brannon Miller,12.0,LinkedIn,Exceeds,4.30,3,0,1/11/2019,0,1
167,"Liebig, Ketsia",10017,1,1,0,1,5,4,0,77915,...,Janet King,2.0,Website,Exceeds,4.10,3,0,1/21/2019,0,11
170,"Lindsay, Leonara",10008,0,0,0,1,3,4,1,51777,...,Eric Dougall,6.0,Diversity Job Fair,Exceeds,4.64,4,5,1/25/2019,0,14
172,"Lunquist, Lisa",10035,0,0,0,1,5,4,0,73330,...,Elijiah Gray,16.0,Indeed,Exceeds,4.20,4,0,2/12/2019,0,19
174,"Lynch, Lindsay",10004,0,0,0,5,5,4,1,47434,...,Webster Butler,39.0,Diversity Job Fair,Exceeds,5.00,4,0,2/2/2015,0,17
191,"Monterro, Luisa",10025,0,0,0,1,5,4,0,72460,...,Kissy Sullivan,20.0,Indeed,Exceeds,4.70,3,0,1/14/2019,0,1
201,"Ngodup, Shari",10037,0,3,0,1,5,4,1,52984,...,Brannon Miller,12.0,Diversity Job Fair,Exceeds,4.00,3,0,2/13/2019,0,12
208,"Osturnka, Adeel",10021,1,1,1,1,5,4,0,47414,...,Kelley Spirea,18.0,LinkedIn,Exceeds,5.00,3,0,2/7/2019,0,13
212,"Patronick, Lucas",10005,0,0,1,5,4,4,1,108987,...,Alex Sweetwater,10.0,Diversity Job Fair,Exceeds,5.00,5,3,8/16/2015,0,13
217,"Peters, Lauren",10032,1,1,0,5,5,4,0,57954,...,Ketsia Liebig,19.0,Indeed,Exceeds,4.20,5,0,1/10/2013,0,12
220,"Petrowsky, Thelma",10016,1,1,0,1,3,4,0,93554,...,Simon Roup,4.0,Employee Referral,Exceeds,4.60,5,7,1/4/2019,0,16
232,"Rivera, Haley",10011,1,1,0,1,5,4,0,46738,...,Webster Butler,NaN,Google Search,Exceeds,4.36,5,0,2/11/2019,0,16
237,"Robinson, Elias",10020,0,4,1,1,5,4,0,63353,...,Brannon Miller,12.0,Employee Referral,Exceeds,3.60,5,0,2/11/2019,0,4
257,"Smith, Joe",10027,0,0,1,1,5,4,0,60656,...,Elijiah Gray,16.0,Indeed,Exceeds,4.30,3,0,1/28/2019,0,4
265,"Squatrito, Kristen",10030,0,2,0,5,5,4,0,62425,...,David Stanley,14.0,LinkedIn,Exceeds,4.10,4,0,3/2/2015,0,16
274,"Szabo, Andrew",10024,0,0,1,1,4,4,0,92989,...,Alex Sweetwater,10.0,LinkedIn,Exceeds,4.50,5,5,2/18/2019,0,1
282,"Torrence, Jack",10013,0,3,1,1,6,4,0,64397,...,Lynn Daneault,21.0,Indeed,Exceeds,4.10,3,0,1/4/2019,0,6
289,"Veera, Abdellah",10014,0,2,1,5,5,4,0,58523,...,Kissy Sullivan,20.0,LinkedIn,Exceeds,4.50,5,0,2/1/2016,0,15
293,"Volk, Colleen",10022,1,1,0,4,5,4,0,49773,...,Kelley Spirea,18.0,Google Search,Exceeds,4.30,5,0,2/1/2015,0,18
304,"Winthrop, Jordan",10033,0,0,1,5,5,4,0,70507,...,Brannon Miller,12.0,LinkedIn,Exceeds,5.00,3,0,1/19/2016,0,7
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16

In [ ]:
# Get all female employees (Sex == 'F').
df[df["Sex"]=='F']

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
5,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
6,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,"Wolk, Hang T",10174,0,0,0,1,5,3,0,60446,...,David Stanley,14.0,LinkedIn,Fully Meets,3.40,4,0,2/21/2019,0,14
307,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

In [ ]:
# Find employees who have more than 5 absences.
df[df["Absences"]>5]

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
5,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
6,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
7,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,"Winthrop, Jordan",10033,0,0,1,5,5,4,0,70507,...,Brannon Miller,12.0,LinkedIn,Exceeds,5.00,3,0,1/19/2016,0,7
305,"Wolk, Hang T",10174,0,0,0,1,5,3,0,60446,...,David Stanley,14.0,LinkedIn,Fully Meets,3.40,4,0,2/21/2019,0,14
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11

In [ ]:
# Filter employees hired after 2015.

import pandas as pd
df[pd.to_datetime(df["DateofHate"]).dt.year > 2015]

KeyError: 'DateofHate'

In [ ]:
# Get employees whose MaritalDesc is 'Single'.
df[df["MaritalDesc"]=='Single']

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
5,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
6,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
8,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,Brannon Miller,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4
13,"Barone, Francesco A",10265,0,0,1,1,5,3,0,58709,...,Kelley Spirea,18.0,Google Search,Fully Meets,4.60,4,0,2/14/2019,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,"Wolk, Hang T",10174,0,0,0,1,5,3,0,60446,...,David Stanley,14.0,LinkedIn,Fully Meets,3.40,4,0,2/21/2019,0,14
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
307,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11

In [ ]:
# Find employees recruited from LinkedIn.
df[df["RecruitmentSource"]=='LinkedIn']

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
5,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
6,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
19,"Becker, Scott",10277,0,0,1,3,5,3,0,53250,...,Webster Butler,NaN,LinkedIn,Fully Meets,4.20,4,0,1/11/2019,0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,"Whittier, Scott",10072,0,0,1,5,5,3,0,58371,...,Webster Butler,39.0,LinkedIn,Fully Meets,5.00,5,0,5/15/2014,0,11
304,"Winthrop, Jordan",10033,0,0,1,5,5,4,0,70507,...,Brannon Miller,12.0,LinkedIn,Exceeds,5.00,3,0,1/19/2016,0,7
305,"Wolk, Hang T",10174,0,0,0,1,5,3,0,60446,...,David Stanley,14.0,LinkedIn,Fully Meets,3.40,4,0,2/21/2019,0,14
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

In [ ]:
# 🔹 B. Sorting
# Sort employees by Salary (highest to lowest).
df.sort_values("Salary",ascending=False)

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
150,"King, Janet",10089,1,1,0,1,2,3,0,250000,...,Board of Directors,9.0,Indeed,Fully Meets,4.83,3,0,1/17/2019,0,10
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
131,"Houlihan, Debra",10272,1,1,0,1,6,3,0,180000,...,Janet King,2.0,LinkedIn,Fully Meets,4.50,4,0,1/21/2019,0,19
96,"Foss, Jason",10015,0,0,1,1,3,4,0,178000,...,Jennifer Zamora,5.0,Indeed,Exceeds,5.00,5,5,1/7/2019,0,15
55,"Corleone, Vito",10019,0,0,1,1,5,4,0,170500,...,Janet King,2.0,Indeed,Exceeds,3.70,5,0,2/4/2019,0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,"Kirill, Alexandra",10170,1,1,0,5,5,3,0,45433,...,Amy Dunn,11.0,Google Search,Fully Meets,3.49,4,0,1/30/2013,0,6
176,"Mahoney, Lauren",10219,0,0,0,1,5,3,0,45395,...,Ketsia Liebig,19.0,LinkedIn,Fully Meets,4.60,4,0,2/26/2019,0,14
231,"Rhoads, Thomas",10058,0,2,1,5,5,3,0,45115,...,Elijiah Gray,16.0,LinkedIn,Fully Meets,5.00,4,0,3/30/2015,0,11
140,"Jacobi, Hannah",10236,0,2,0,1,5,3,0,45069,...,Kissy Sullivan,20.0,Employee Referral,Fully Meets,4.30,5,0,2/22/2019,0,7
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

In [ ]:
# Sort employees by DateofHire (oldest first).
df["DateofHire"]=pd.to_datetime(df["DateofHire"])
df.sort_values("DateofHire", ascending = True)[["DateofHire", "Employee_Name"]]

    DateofHire       Employee_Name
282 2006-01-09      Torrence, Jack
280 2007-06-25    Thibaud, Kenneth
222 2007-11-05         Pitt, Brad
3   2008-01-07        Alagbe,Trina
307 2008-09-02  Ybarra, Catherine
..         ...                 ...
298 2017-02-15       Wang, Charlie
70  2017-02-15       DeVito, Tommy
275 2017-04-20        Tannen, Biff
120 2017-04-20        Gruber, Hans
64  2018-07-09          Dee, Randy

[311 rows x 2 columns]

In [ ]:
# Sort employees by Absences and Salary together.

df.sort_values(["Absences","Salary"], ascending = [True,True])[["Employee_Name","Absences","Salary"]]

               Employee_Name  Absences  Salary
126        Heitzman, Anthony         1   46998
279       Theamstern, Sophia         1   48413
71         Dickinson, Geoff          1   51259
14             Barton, Nader         1   52505
62          Darson, Jene'ya          1   57583
..                       ...       ...     ...
155          Kreuger, Freddy        20   71339
121          Guilianno, Mike        20   71707
93   Fitzpatrick, Michael  J        20   72609
109              Goeth, Amon        20   74679
164      LeBlanc, Brandon  R        20   93046

[311 rows x 3 columns]

In [ ]:
# Get the top 5 highest-paid employees.
df.sort_values("Salary", ascending = False).head(5)

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
150,"King, Janet",10089,1,1,0,1,2,3,0,250000,...,Board of Directors,9.0,Indeed,Fully Meets,4.83,3,0,1/17/2019,0,10
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
131,"Houlihan, Debra",10272,1,1,0,1,6,3,0,180000,...,Janet King,2.0,LinkedIn,Fully Meets,4.50,4,0,1/21/2019,0,19
96,"Foss, Jason",10015,0,0,1,1,3,4,0,178000,...,Jennifer Zamora,5.0,Indeed,Exceeds,5.00,5,5,1/7/2019,0,15
55,"Corleone, Vito",10019,0,0,1,1,5,4,0,170500,...,Janet King,2.0,Indeed,Exceeds,3.70,5,0,2/4/2019,0,15

In [ ]:
# Get the 5 employees with the highest absences.
df.sort_values("Absences", ascending = False).head(5)

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
263,"Sparks, Taylor",10302,1,1,0,1,5,1,0,64021,...,Brannon Miller,12.0,Indeed,PIP,2.40,2,1,2/25/2019,6,20
256,"Sloan, Constance",10095,0,0,0,5,5,3,0,63878,...,Michael Albert,22.0,CareerBuilder,Fully Meets,4.68,4,0,4/2/2015,0,20
93,"Fitzpatrick, Michael J",10093,0,0,1,5,5,3,0,72609,...,Amy Dunn,11.0,Google Search,Fully Meets,4.76,5,0,4/5/2013,0,20
161,"Latif, Mohammed",10249,1,1,1,5,5,3,0,61962,...,Kissy Sullivan,20.0,Google Search,Fully Meets,4.90,3,0,2/20/2013,0,20
121,"Guilianno, Mike",10109,0,0,1,5,6,3,0,71707,...,John Smith,17.0,LinkedIn,Fully Meets,4.50,5,0,2/1/2013,0,20

In [ ]:
# 🔹 C. GroupBy (Beginner)

# Find the average salary per department.
df.groupby("Department").agg(Average_salary = ("Salary","mean")).reset_index()

             Department  Average_salary
0         Admin Offices    71791.888889
1      Executive Office   250000.000000
2                 IT/IS    97064.640000
3     Production           59953.545455
4                 Sales    69061.258065
5  Software Engineering    94989.454545

In [ ]:
# Count number of employees in each department.
df.groupby("Department").agg(total_employees = ("EmpID","count")).reset_index()

             Department  total_employees
0         Admin Offices                9
1      Executive Office                1
2                 IT/IS               50
3     Production                     209
4                 Sales               31
5  Software Engineering               11

In [ ]:
# Find maximum salary per Position.
df.groupby("Position").agg(Average_salary = ("Salary","max")).reset_index().sort_values("Average_salary", ascending = False)

                        Position  Average_salary
19               President & CEO          250000
5                            CIO          220450
11             Director of Sales          180000
13                   IT Director          178000
10        Director of Operations          170500
15            IT Manager - Infra          157000
8                 Data Architect          150290
14               IT Manager - DB          148999
16          IT Manager - Support          138888
20      Principal Data Architect          120000
9         Database Administrator          114800
4                    BI Director          110929
27             Software Engineer          108987
31          Sr. Network Engineer          107226
29                Sr. Accountant          106367
30                       Sr. DBA          104437
12          Enterprise Architect          103613
3                   BI Developer           99020
6                   Data Analyst           93554
26       Shared Services Manager           93046
21            Production Manager           88976
7                  Data Analyst            88527
25           Senior BI Developer           87921
28  Software Engineering Manager           77692
18              Network Engineer           76029
23      Production Technician II           74813
17                    IT Support           74679
2             Area Sales Manager           74326
24                 Sales Manager           72992
22       Production Technician I           64991
0                   Accountant I           64520
1       Administrative Assistant           55000

In [ ]:
# Count employees by Gender.
df.groupby("Sex").agg(total_employees = ("sex","count")).reset_index()

KeyError: "Column(s) ['sex'] do not exist"

In [ ]:
# Get average engagement score per department.
df.groupby("Department").agg(Average_engagement = ("EngagementSurvey","mean")).reset_index()

             Department  Average_engagement
0         Admin Offices            4.393333
1      Executive Office            4.830000
2                 IT/IS            4.154000
3     Production                   4.129569
4                 Sales            3.818710
5  Software Engineering            4.061818

In [ ]:
# 🔹 D. Creating New Columns

# Create a new column AnnualBonus as 10% of Salary.
df["AnnualBonus"] = df["Salary"]*0.1
df[["AnnualBonus","Salary"]]

     AnnualBonus  Salary
0         6250.6   62506
1        10443.7  104437
2         6495.5   64955
3         6499.1   64991
4         5082.5   50825
..           ...     ...
306       6589.3   65893
307       4851.3   48513
308      22045.0  220450
309       8929.2   89292
310       4504.6   45046

[311 rows x 2 columns]

In [ ]:
# Create a column HighSalary → True if salary > 70000 else False.
df["HighSalary"] = df["Salary"] > 70000
df[["HighSalary","Salary"]]

     HighSalary  Salary
0         False   62506
1          True  104437
2         False   64955
3         False   64991
4         False   50825
..          ...     ...
306       False   65893
307       False   48513
308        True  220450
309        True   89292
310       False   45046

[311 rows x 2 columns]

In [ ]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Sex', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'AnnualBonus', 'HighSalary'],
      dtype='object')

In [ ]:
# Create a column IsTerminated from Termd.

df["IsTerminated"] = df["Termd"].apply(lambda x: True if x == 1 else False)
df[["IsTerminated","Termd"]]

     IsTerminated  Termd
0           False      0
1            True      1
2            True      1
3           False      0
4            True      1
..            ...    ...
306         False      0
307          True      1
308         False      0
309         False      0
310         False      0

[311 rows x 2 columns]

In [ ]:
# Create a column LateRisk → True if DaysLateLast30 > 3.
df["LateRisk"] = df["DaysLateLast30"] > 3
df[["LateRisk","DaysLateLast30"]]

     LateRisk  DaysLateLast30
0       False               0
1       False               0
2       False               0
3       False               0
4       False               0
..        ...             ...
306     False               0
307      True               5
308     False               0
309     False               0
310     False               0

[311 rows x 2 columns]

In [ ]:
def LR(a):
  if a > 3:
    return True
  else:
    return False

df["LateRisk1"] = df["DaysLateLast30"].apply(LR)
df[["LateRisk1","DaysLateLast30"]]

     LateRisk1  DaysLateLast30
0        False               0
1        False               0
2        False               0
3        False               0
4        False               0
..         ...             ...
306      False               0
307       True               5
308      False               0
309      False               0
310      False               0

[311 rows x 2 columns]

In [ ]:
df["LateRisk"]=df["DaysLateLast30"].apply(lambda x : "LateRisk" if x>3 else "No LateRisk")
df[["LateRisk","DaysLateLast30"]]

        LateRisk  DaysLateLast30
0    No LateRisk               0
1    No LateRisk               0
2    No LateRisk               0
3    No LateRisk               0
4    No LateRisk               0
..           ...             ...
306  No LateRisk               0
307     LateRisk               5
308  No LateRisk               0
309  No LateRisk               0
310  No LateRisk               0

[311 rows x 2 columns]

In [ ]:
# Create a column SatisfactionLevel:
# High → EmpSatisfaction ≥ 4
# Medium → EmpSatisfaction = 3
# Low → EmpSatisfaction ≤ 2
df["SatisfactionLevel"] = df["EmpSatisfaction"].apply(lambda x: "High" if x >= 4 else "Medium" if x == 3 else "Low")
df[["EmpSatisfaction","SatisfactionLevel"]]

     EmpSatisfaction SatisfactionLevel
0                  5              High
1                  3            Medium
2                  3            Medium
3                  5              High
4                  4              High
..               ...               ...
306                4              High
307                2               Low
308                5              High
309                3            Medium
310                5              High

[311 rows x 2 columns]

In [ ]:
def satisfaction_level(a):
  if a >= 4:
    return "High"
  elif a == 3:
    return "Medium"
  else:
    return "Low"

df["SatisfactionLevel1"] = df["EmpSatisfaction"].apply(satisfaction_level)
df[["EmpSatisfaction","SatisfactionLevel1"]]

     EmpSatisfaction SatisfactionLevel1
0                  5               High
1                  3             Medium
2                  3             Medium
3                  5               High
4                  4               High
..               ...                ...
306                4               High
307                2                Low
308                5               High
309                3             Medium
310                5               High

[311 rows x 2 columns]

In [ ]:
[f"{i}-{len(i)}" for i in df["Position"].unique()]

['Production Technician I-23',
 'Sr. DBA-7',
 'Production Technician II-24',
 'Software Engineer-17',
 'IT Support-10',
 'Data Analyst-12',
 'Database Administrator-22',
 'Enterprise Architect-20',
 'Sr. Accountant-14',
 'Production Manager-18',
 'Accountant I-12',
 'Area Sales Manager-18',
 'Software Engineering Manager-28',
 'BI Director-11',
 'Director of Operations-22',
 'Sr. Network Engineer-20',
 'Sales Manager-13',
 'BI Developer-12',
 'IT Manager - Support-20',
 'Network Engineer-16',
 'IT Director-11',
 'Director of Sales-17',
 'Administrative Assistant-24',
 'President & CEO-15',
 'Senior BI Developer-19',
 'Shared Services Manager-23',
 'IT Manager - Infra-18',
 'Principal Data Architect-24',
 'Data Architect-14',
 'IT Manager - DB-15',
 'Data Analyst -13',
 'CIO-3']

In [ ]:
df["Position"] = [i.replace("t ","t") for i in df["Position"]]

In [ ]:
[f"{i}-{len(i)}" for i in df["Position"].unique()]

['Production Technician I-23',
 'Sr. DBA-7',
 'Production Technician II-24',
 'Software Engineer-17',
 'IT Support-10',
 'Data Analyst-12',
 'Database Administrator-22',
 'Enterprise Architect-20',
 'Sr. Accountant-14',
 'Production Manager-18',
 'AccountantI-11',
 'Area Sales Manager-18',
 'Software Engineering Manager-28',
 'BI Director-11',
 'Director of Operations-22',
 'Sr. Network Engineer-20',
 'Sales Manager-13',
 'BI Developer-12',
 'IT Manager - Support-20',
 'Network Engineer-16',
 'IT Director-11',
 'Director of Sales-17',
 'Administrative Assistant-24',
 'President& CEO-14',
 'Senior BI Developer-19',
 'Shared Services Manager-23',
 'IT Manager - Infra-18',
 'Principal Data Architect-24',
 'Data Architect-14',
 'IT Manager - DB-15',
 'CIO-3']

In [ ]:
# 🔹 E. Function-based (apply / lambda)

# Create a function to classify salary:

# Low < 50k

# Medium 50k–80k

# High > 80k
# Apply it to create SalaryCategory.

def classify_salary(a):
  if a < 50000:
    return "Low"
  elif a >= 50000 and a <= 80000:
    return "Medium"
  elif a > 80000:
    return "High"

df["SalaryCategory"] = df["Salary"].apply(classify_salary)
df[["Salary","SalaryCategory"]]

lambda x: "Low" if x < 50000 else "Medium" if x >= 50000 and x <= 80000 else "High"

In [ ]:

df["SalaryCategory"] = df["Salary"].apply(lambda x: "Low" if x < 50000 else "Medium" if x >= 50000 and x <= 80000 else "High")
df[["Salary","SalaryCategory"]]

     Salary SalaryCategory
0     62506         Medium
1    104437           High
2     64955         Medium
3     64991         Medium
4     50825         Medium
..      ...            ...
306   65893         Medium
307   48513            Low
308  220450           High
309   89292           High
310   45046            Low

[311 rows x 2 columns]

In [ ]:
# Write a function to calculate experience in years from DateofHire.



def exp(y):
  if y == "null":
    return (pd.Timestep("today") - pd.to_datetime(df["DateofHire"])).days/365
  else:
    return (pd.to_datetime(df["DateofTermination"])- pd.to_datetime(df["DateofHire"])).days/365


df["Experience"] = df["DateofHire"].apply(exp)
df[["DateofHire","Experience"]]

AttributeError: 'Series' object has no attribute 'days'

In [ ]:
df[df["DateofTermination"].isna()]

#isna => is null
#create a dataframe => for the active employees
#create a years of experience
#department wise avg experience

#terminated
(pd.Timestep("today") - pd.to_datetime("2011-01-01")).days/365

#which department

AttributeError: module 'pandas' has no attribute 'Timestep'

In [ ]:
df1 = df[df["DateofTermination"].isna()]
c_date = pd.Timestamp("today")

df["no_of_days_worked"] = (pd.Timestamp("today")- df["DateofHire"]).dt.days
df["no_of_days_worked"] = round(df["no_of_days_worked"]/365,2)

In [ ]:
df1.groupby("Department").agg(Average_Tears = ("no_of_days_worked","mean")).reset_index()

KeyError: "Column(s) ['no_of_days_worked'] do not exist"

In [ ]:

df["PerformanceFlag"] = df["Absences"].apply(lambda x: "Risk" if x > 10 else "Safe")
df[["Absences","PerformanceFlag"]].head()

   Absences PerformanceFlag
0         1            Safe
1        17            Risk
2         3            Safe
3        15            Risk
4         2            Safe

In [ ]:
# Create a function that returns "Risk" if absences > 10 else "Safe".
def risk(a):
  if a > 10:
    return "Risk"
  else:
    return "Safe"

df["Risk"] = df["Absences"].apply(risk)
df[["Absences","Risk"]].head()

   Absences  Risk
0         1  Safe
1        17  Risk
2         3  Safe
3        15  Risk
4         2  Safe

In [ ]:
def PerformanceScore(a):
  if a == "Exceeds" or a == "Fully Meets":
    return 1
  else:
    return 0

df["PerformanceScore1"] = df["PerformanceScore"].apply(PerformanceScore)
df[["PerformanceScore","PerformanceScore1"]]

    PerformanceScore  PerformanceScore1
0            Exceeds                  1
1        Fully Meets                  1
2        Fully Meets                  1
3        Fully Meets                  1
4        Fully Meets                  1
..               ...                ...
306      Fully Meets                  1
307              PIP                  0
308          Exceeds                  1
309      Fully Meets                  1
310      Fully Meets                  1

[311 rows x 2 columns]

In [ ]:

df["PerformanceScore_num"] = df["PerformanceScore"].apply(lambda x: 1 if x == "Exceeds" or x == "Fully Meets" else 0)
df[["PerformanceScore","PerformanceScore_num"]]

    PerformanceScore  PerformanceScore_num
0            Exceeds                     1
1        Fully Meets                     1
2        Fully Meets                     1
3        Fully Meets                     1
4        Fully Meets                     1
..               ...                   ...
306      Fully Meets                     1
307              PIP                     0
308          Exceeds                     1
309      Fully Meets                     1
310      Fully Meets                     1

[311 rows x 2 columns]

In [ ]:
# Create a function to check diversity hire (FromDiversityJobFairID == 1).

def diversity_hire(a):
  if a == 1:
    return True
  else:
    return False

df["DiversityHire"] = df["FromDiversityJobFairID"].apply(diversity_hire)
df[["FromDiversityJobFairID","DiversityHire"]]

     FromDiversityJobFairID  DiversityHire
0                         0          False
1                         0          False
2                         0          False
3                         0          False
4                         0          False
..                      ...            ...
306                       0          False
307                       0          False
308                       0          False
309                       0          False
310                       0          False

[311 rows x 2 columns]

In [ ]:

df["DiversityHire"] = df["FromDiversityJobFairID"].apply(lambda x: True if x == 1 else False)
df[["FromDiversityJobFairID","DiversityHire"]]

     FromDiversityJobFairID  DiversityHire
0                         0          False
1                         0          False
2                         0          False
3                         0          False
4                         0          False
..                      ...            ...
306                       0          False
307                       0          False
308                       0          False
309                       0          False
310                       0          False

[311 rows x 2 columns]

In [ ]:
# ❓ Case Study Questions (Pandas Required)

# Which city’s employees enrolled after the webinar date?
# (Hint: compare enrolled_date and webinar_date)

# Find the number of employees enrolled per webinar.

# Which city has the highest number of enrollments overall?

# Calculate the attendance rate (%) for each webinar.

# List employees who enrolled but did not attend any webinar.

# Identify the most popular webinar topic based on enrollments.

# Which city has the highest attendance count?

# Find employees who enrolled before the webinar date but attended.

# For each webinar, calculate:

# Total enrolled

# Total attended

# Based on attendance and enrollment trends, which city should be targeted for the next webinar and why?
# (Inference required, not just numbers)

In [ ]:
import pandas as pd
import numpy as np

# ---------------------------
# Webinar Data (22 webinars)
# ---------------------------
webinar_df = pd.DataFrame({
    "webinar_id": range(101, 123),
    "webinar_name": [
        "Python Basics", "Advanced Python", "Data Analytics Fundamentals",
        "Power BI Essentials", "SQL for Analysts", "HR Analytics",
        "AI for Business", "Python for Data Science", "Dashboard Design",
        "SQL Optimization", "People Analytics", "Machine Learning Intro",
        "Data Storytelling", "Power BI Advanced", "AI Ethics",
        "Predictive Analytics", "Python Automation", "HR Metrics",
        "Business Intelligence", "SQL Joins Deep Dive",
        "Analytics for Managers", "AI in HR"
    ],
    "webinar_date": pd.date_range(start="2024-01-06", periods=22, freq="7D"),
    "topic": [
        "Python","Python","Data Analytics","Power BI","SQL","HR Analytics",
        "AI","Python","Power BI","SQL","HR Analytics","AI",
        "Data Analytics","Power BI","AI","Data Analytics",
        "Python","HR Analytics","Power BI","SQL",
        "Data Analytics","AI"
    ]
})


# ---------------------------------
# Employee Enrollment Data (35 rows)
# ---------------------------------
employee_enrolled_df = pd.DataFrame({
    "emp_id": range(201, 236),
    "emp_name": [
        "Ahmad","Siti","Aisyah","Daniel","Aiman","Nur","Farah","Hafiz","Aina",
        "Syafiq","Nabila","Irfan","Amirah","Faiz","Aqilah","Hakim","Alya",
        "Zarul","Nadiah","Arif","Sofia","Kamal","Liyana","Firdaus",
        "Haziq","Mira","Azlan","Yasmin","Fatin","Rizal",
        "Shafiq","Huda","Imran","Athirah","Zain"
    ],
    "city": [
        "Kuala Lumpur","Kuala Lumpur","Selangor","Selangor","Kuala Lumpur",
        "Penang","Johor Bahru","Selangor","Cyberjaya",
        "Kuala Lumpur","Putrajaya","Selangor","Melaka","Penang",
        "Johor Bahru","Kuala Lumpur","Selangor",
        "Cyberjaya","Putrajaya","Kuala Lumpur",
        "Selangor","Penang","Melaka","Johor Bahru",
        "Kuala Lumpur","Selangor","Putrajaya","Cyberjaya",
        "Penang","Johor Bahru",
        "Kuala Lumpur","Selangor","Cyberjaya","Melaka","Penang"
    ],
    "webinar_id": [
        101,102,103,104,105,106,107,108,109,
        110,111,112,113,114,115,116,117,
        118,119,120,121,122,101,102,
        103,104,105,106,107,108,
        109,110,111,112,113
    ],
    # Mostly enrolled AFTER webinar date (3–10 days)
    "enrolled_date": [
        "2024-01-15","2024-01-23","2024-01-30","2024-02-07","2024-02-14",
        "2024-02-21","2024-02-28","2024-03-06","2024-03-13",
        "2024-03-20","2024-03-27","2024-04-03","2024-04-10",
        "2024-04-17","2024-04-24","2024-05-01","2024-05-08",
        "2024-05-15","2024-05-22","2024-05-29",
        "2024-06-05","2024-06-12",
        "2024-01-16","2024-01-24",
        "2024-01-31","2024-02-08","2024-02-15",
        "2024-02-22","2024-03-01","2024-03-08",
        "2024-03-14","2024-03-21",
        "2024-03-28","2024-04-04","2024-04-11"
    ],
    # High attendance, very few anomalies
    "attended": [
        "Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes",
        "Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes",
        "Yes","Yes","No","Yes","Yes","Yes","Yes","Yes","Yes","Yes",
        "Yes","Yes","Yes","Yes","Yes"
    ]
})

employee_enrolled_df["enrolled_date"] = pd.to_datetime(employee_enrolled_df["enrolled_date"])

In [ ]:
webinar_df

    webinar_id                 webinar_name webinar_date           topic
0          101                Python Basics   2024-01-06          Python
1          102              Advanced Python   2024-01-13          Python
2          103  Data Analytics Fundamentals   2024-01-20  Data Analytics
3          104          Power BI Essentials   2024-01-27        Power BI
4          105             SQL for Analysts   2024-02-03             SQL
5          106                 HR Analytics   2024-02-10    HR Analytics
6          107              AI for Business   2024-02-17              AI
7          108      Python for Data Science   2024-02-24          Python
8          109             Dashboard Design   2024-03-02        Power BI
9          110             SQL Optimization   2024-03-09             SQL
10         111             People Analytics   2024-03-16    HR Analytics
11         112       Machine Learning Intro   2024-03-23              AI
12         113            Data Storytelling   2024-03-30  Data Analytics
13         114            Power BI Advanced   2024-04-06        Power BI
14         115                    AI Ethics   2024-04-13              AI
15         116         Predictive Analytics   2024-04-20  Data Analytics
16         117            Python Automation   2024-04-27          Python
17         118                   HR Metrics   2024-05-04    HR Analytics
18         119        Business Intelligence   2024-05-11        Power BI
19         120          SQL Joins Deep Dive   2024-05-18             SQL
20         121       Analytics for Managers   2024-05-25  Data Analytics
21         122                     AI in HR   2024-06-01              AI

In [ ]:
employee_enrolled_df

    emp_id emp_name          city  webinar_id enrolled_date attended
0      201    Ahmad  Kuala Lumpur         101    2024-01-15      Yes
1      202     Siti  Kuala Lumpur         102    2024-01-23      Yes
2      203   Aisyah      Selangor         103    2024-01-30      Yes
3      204   Daniel      Selangor         104    2024-02-07      Yes
4      205    Aiman  Kuala Lumpur         105    2024-02-14      Yes
5      206      Nur        Penang         106    2024-02-21      Yes
6      207    Farah   Johor Bahru         107    2024-02-28      Yes
7      208    Hafiz      Selangor         108    2024-03-06      Yes
8      209     Aina     Cyberjaya         109    2024-03-13      Yes
9      210   Syafiq  Kuala Lumpur         110    2024-03-20      Yes
10     211   Nabila     Putrajaya         111    2024-03-27      Yes
11     212    Irfan      Selangor         112    2024-04-03      Yes
12     213   Amirah        Melaka         113    2024-04-10      Yes
13     214     Faiz        Penang         114    2024-04-17      Yes
14     215   Aqilah   Johor Bahru         115    2024-04-24      Yes
15     216    Hakim  Kuala Lumpur         116    2024-05-01      Yes
16     217     Alya      Selangor         117    2024-05-08      Yes
17     218    Zarul     Cyberjaya         118    2024-05-15      Yes
18     219   Nadiah     Putrajaya         119    2024-05-22      Yes
19     220     Arif  Kuala Lumpur         120    2024-05-29      Yes
20     221    Sofia      Selangor         121    2024-06-05      Yes
21     222    Kamal        Penang         122    2024-06-12      Yes
22     223   Liyana        Melaka         101    2024-01-16       No
23     224  Firdaus   Johor Bahru         102    2024-01-24      Yes
24     225    Haziq  Kuala Lumpur         103    2024-01-31      Yes
25     226     Mira      Selangor         104    2024-02-08      Yes
26     227    Azlan     Putrajaya         105    2024-02-15      Yes
27     228   Yasmin     Cyberjaya         106    2024-02-22      Yes
28     229    Fatin        Penang         107    2024-03-01      Yes
29     230    Rizal   Johor Bahru         108    2024-03-08      Yes
30     231   Shafiq  Kuala Lumpur         109    2024-03-14      Yes
31     232     Huda      Selangor         110    2024-03-21      Yes
32     233    Imran     Cyberjaya         111    2024-03-28      Yes
33     234  Athirah        Melaka         112    2024-04-04      Yes
34     235     Zain        Penang         113    2024-04-11      Yes

In [ ]:
# Which webinar topic converts best (highest enrollments)?

df1 = pd.merge(webinar_df,employee_enrolled_df,left_on = "webinar_id",right_on = "webinar_id",how = "right")
df1.groupby("webinar_name").agg(total_enrolled = ("emp_name","count")).reset_index().sort_values("total_enrolled",ascending = False)
#

                   webinar_name  total_enrolled
1               AI for Business               2
3               Advanced Python               2
9                  HR Analytics               2
8             Data Storytelling               2
7   Data Analytics Fundamentals               2
6              Dashboard Design               2
21             SQL for Analysts               2
18      Python for Data Science               2
20             SQL Optimization               2
14          Power BI Essentials               2
11       Machine Learning Intro               2
12             People Analytics               2
17                Python Basics               2
0                     AI Ethics               1
5         Business Intelligence               1
4        Analytics for Managers               1
2                      AI in HR               1
10                   HR Metrics               1
13            Power BI Advanced               1
15         Predictive Analytics               1
16            Python Automation               1
19          SQL Joins Deep Dive               1

In [ ]:
# ❓ Case Study Questions (Pandas Required)

# Which city has the highest number of webinar enrollments?
df1 = pd.merge(webinar_df,employee_enrolled_df,left_on = "webinar_id",right_on = "webinar_id",how = "right")
df2 = df1.groupby("city").agg(total_enrolled = ("emp_name","count")).reset_index()
df2.sort_values("total_enrolled",ascending = False)

           city  total_enrolled
2  Kuala Lumpur               8
6      Selangor               8
4        Penang               5
1   Johor Bahru               4
0     Cyberjaya               4
3        Melaka               3
5     Putrajaya               3

In [98]:
# Do employees generally enroll after attending the webinar? Prove using dates.
df1 = pd.merge(webinar_df,employee_enrolled_df,left_on = "webinar_id",right_on = "webinar_id",how = "right")
w_d = df1["webinar_date"]
def enroll_after_attending(a):
  if a >= w_d:
    return True
  else:
    return False

df1["enroll_after_attending"] = df1["enrolled_date"].apply(enroll_after_attending)
df1[["enrolled_date","enroll_after_attending"]]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [106]:
# Compare Kuala Lumpur vs Selangor in terms of:

# Enrollment count
# Attendance rate
df1 = pd.merge(webinar_df,employee_enrolled_df,left_on = "webinar_id",right_on = "webinar_id",how = "right")
df2 = df1[(df1["city"] == "Kuala Lumpur") | (df1["city"] == "Selangor")]

df3 = df2.groupby("city").agg(Enrollment_count = ("emp_name","count"), Attendance = ("attended","count")).reset_index()
df3["Percentage"] = round(df3["Attendance"]/df3["Enrollment_count"]*100,2)
df3

           city  Enrollment_count  Attendance  Percentage
0  Kuala Lumpur                 8           8       100.0
1      Selangor                 8           8       100.0

In [115]:
# Which city shows the highest post-webinar conversion?
df1 = pd.merge(webinar_df,employee_enrolled_df,left_on = "webinar_id",right_on = "webinar_id",how = "right")
def pw_con(a):
  count = 0
  if a == "Yes":
    count += 1
    return count
  else:
    return 0

df1["total_enrolled"] = df1["attended"].apply(pw_con)
df1.groupby("city").agg(total_enrolled = ("total_enrolled","sum")).reset_index().sort_values("total_enrolled",ascending = False).head()

           city  total_enrolled
2  Kuala Lumpur               8
6      Selangor               8
4        Penang               5
1   Johor Bahru               4
0     Cyberjaya               4

In [125]:
# Identify any anomalies in enrollment or attendance behavior.
df1 = pd.merge(webinar_df,employee_enrolled_df,left_on = "webinar_id",right_on = "webinar_id",how = "right")
df1

,webinar_id,webinar_name,webinar_date,topic,emp_id,emp_name,city,enrolled_date,attended
0,101,Python Basics,2024-01-06,Python,201,Ahmad,Kuala Lumpur,2024-01-15,Yes
1,102,Advanced Python,2024-01-13,Python,202,Siti,Kuala Lumpur,2024-01-23,Yes
2,103,Data Analytics Fundamentals,2024-01-20,Data Analytics,203,Aisyah,Selangor,2024-01-30,Yes
3,104,Power BI Essentials,2024-01-27,Power BI,204,Daniel,Selangor,2024-02-07,Yes
4,105,SQL for Analysts,2024-02-03,SQL,205,Aiman,Kuala Lumpur,2024-02-14,Yes
5,106,HR Analytics,2024-02-10,HR Analytics,206,Nur,Penang,2024-02-21,Yes
6,107,AI for Business,2024-02-17,AI,207,Farah,Johor Bahru,2024-02-28,Yes
7,108,Python for Data Science,2024-02-24,Python,208,Hafiz,Selangor,2024-03-06,Yes
8,109,Dashboard Design,2024-03-02,Power BI,209,Aina,Cyberjaya,2024-03-13,Yes
9,110,SQL Optimization,2024-03-09,SQL,210,Syafiq,Kuala Lumpur,2024-03-20,Yes
10,111,People Analytics,2024-03-16,HR Analytics,211,Nabila,Putrajaya,2024-03-27,Yes
11,112,Machine Learning Intro,2024-03-23,AI,212,Irfan,Selangor,2024-04-03,Yes
12,113,Data Storytelling,2024-03-30,Data Analytics,213,Amirah,Melaka,2024-04-10,Yes
13,114,Power BI Advanced,2024-04-06,Power BI,214,Faiz,Penang,2024-04-17,Yes
14,115,AI Ethics,2024-04-13,AI,215,Aqilah,Johor Bahru,2024-04-24,Yes
15,116,Predictive Analytics,2024-04-20,Data Analytics,216,Hakim,Kuala Lumpur,2024-05-01,Yes
16,117,Python Automation,2024-04-27,Python,217,Alya,Selangor,2024-05-08,Yes
17,118,HR Metrics,2024-05-04,HR Analytics,218,Zarul,Cyberjaya,2024-05-15,Yes
18,119,Business Intelligence,2024-05-11,Power BI,219,Nadiah,Putrajaya,2024-05-22,Yes
19,120,SQL Joins Deep Dive,2024-05-18,SQL,220,Arif,Kuala Lumpur,2024-05-29,Yes
20,121,Analytics for Managers,2024-05-25,Data Analytics,221,Sofia,Selangor,2024-06-05,Yes
21,122,AI in HR,2024-06-01,AI,222,Kamal,Penang,2024-06-12,Yes
22,101,Python Basics,2024-01-06,Python,223,Liyana,Melaka,2024-01-16,No
23,102,Advanced Python,2024-01-13,Python,224,Firdaus,Johor Bahru,2024-01-24,Yes
24,103,Data Analytics Fundamentals,2024-01-20,Data Analytics,225,Haziq,Kuala Lumpur,2024-01-31,Yes
25,104,Power BI Essentials,2024-01-27,Power BI,226,Mira,Selangor,2024-02-08,Yes
26,105,SQL for Analysts,2024-02-03,SQL,227,Azlan,Putrajaya,2024-02-15,Yes
27,106,HR Analytics,2024-02-10,HR Analytics,228,Yasmin,Cyberjaya,2024-02-22,Yes
28,107,AI for Business,2024-02-17,AI,229,Fatin,Penang,2024-03-01,Yes
29,108,Python for Data Science,2024-02-24,Python,230,Rizal,Johor Bahru,2024-03-08,Yes
30,109,Dashboard Design,2024-03-02,Power BI,231,Shafiq,Kuala Lumpur,2024-03-14,Yes
31,110,SQL Optimization,2024-03-09,SQL,232,Huda,Selangor,2024-03-21,Yes
32,111,People Analytics,2024-03-16,HR Analytics,233,Imran,Cyberjaya,2024-03-28,Yes
33,112,Machine Learning Intro,2024-03-23,AI,234,Athirah,Melaka,2024-04-04,Yes
34,113,Data Storytelling,2024-03-30,Data Analytics,235,Zain,Penang,2024-04-11,Yes

In [124]:
# Which webinar(s) had full attendance?
df1 = pd.merge(webinar_df,employee_enrolled_df,left_on = "webinar_id",right_on = "webinar_id",how = "right")
def att(a):
  count = 0
  if a == "Yes":
    count += 1
    return count
  else:
    return 0
df1["Total_attendance"] = df1["attended"].apply(att)
df2 = df1.groupby("webinar_name").agg(sum_attendance = ("Total_attendance","sum")).reset_index()
df2[df2['sum_attendance'] ==  2]

                   webinar_name  sum_attendance
1               AI for Business               2
3               Advanced Python               2
6              Dashboard Design               2
7   Data Analytics Fundamentals               2
8             Data Storytelling               2
9                  HR Analytics               2
11       Machine Learning Intro               2
12             People Analytics               2
14          Power BI Essentials               2
18      Python for Data Science               2
20             SQL Optimization               2
21             SQL for Analysts               2