In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [1]:
import pandas as pd

sheet_id = "1MvO7bmVEjlu3EOY_lxDrwQjQ0dBeH97gHkOL6aYBxJc"
sheet_name = "Sheet1"  # change if ur tab name is different

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
df = pd.read_csv(url)

df

          make   model  year  mileage  price   color state
0    Chevrolet   Cruze  2011    99157  37488   white    TX
1       Toyota   Cruze  2017    19882  34176     red    IL
2    Chevrolet  Altima  2011    77718  40297    blue    CA
3       Nissan  Fusion  2012    83613  43492  silver    TX
4         Ford   Cruze  2016    95349  26655     red    NY
..         ...     ...   ...      ...    ...     ...   ...
995      Honda  Altima  2017    25154  43139     red    FL
996  Chevrolet  Accord  2017    68264  15632   white    TX
997     Nissan   Cruze  2016    17417  30832  silver    IL
998      Honda  Accord  2011    68878  10801    blue    TX
999  Chevrolet   Cruze  2010    99313  31827   black    CA

[1000 rows x 7 columns]

In [ ]:
def car(a, b):
  df1 = df[(df["color"] == a) & (df["make"] == b)]
  return df1

In [ ]:
car("silver","Honda")

      make   model  year  mileage  price   color state
22   Honda   Cruze  2011    51408  46098  silver    CA
30   Honda   Camry  2016    12078  22661  silver    FL
56   Honda  Altima  2014    78020  24800  silver    TX
118  Honda   Cruze  2015    80746  13727  silver    CA
125  Honda  Altima  2011    46570  15269  silver    NY
134  Honda   Camry  2018    93813  14436  silver    TX
219  Honda  Altima  2013    52329  41088  silver    TX
230  Honda   Camry  2015    20789  45564  silver    FL
238  Honda  Altima  2011    66092  40552  silver    TX
275  Honda   Camry  2015    18206  49971  silver    CA
379  Honda   Cruze  2013    62284  14828  silver    TX
416  Honda  Fusion  2017    33834  23886  silver    CA
419  Honda  Altima  2011    97849  22338  silver    FL
433  Honda  Altima  2012    69083  33518  silver    TX
449  Honda   Cruze  2015    46781  10972  silver    CA
480  Honda  Accord  2011    95431  44328  silver    IL
506  Honda  Fusion  2015    50841  14419  silver    NY
524  Honda   Cruze  2011    96442  46996  silver    CA
546  Honda  Fusion  2018    16069  24439  silver    CA
556  Honda  Accord  2011    42618  15403  silver    NY
561  Honda  Accord  2017    18722  45798  silver    TX
587  Honda  Accord  2013    35840  44838  silver    IL
659  Honda   Camry  2017    43095  45353  silver    CA
712  Honda   Camry  2013    90392  28391  silver    CA
713  Honda   Cruze  2016    54801  17990  silver    FL
715  Honda  Accord  2010    16598  48900  silver    TX
749  Honda   Cruze  2017    87423  47348  silver    NY
789  Honda  Fusion  2014    77555  15880  silver    TX
792  Honda   Camry  2013    77144  37003  silver    IL
799  Honda  Fusion  2016    55635  15289  silver    CA
808  Honda   Camry  2015    43742  41587  silver    TX
811  Honda   Camry  2011    55769  19553  silver    CA
820  Honda  Fusion  2011    68596  37208  silver    FL
825  Honda   Cruze  2014    33493  11921  silver    NY
833  Honda  Accord  2016    90679  21621  silver    FL
836  Honda  Accord  2013    73801  43499  silver    TX
837  Honda  Accord  2017    54386  12271  silver    TX
850  Honda  Accord  2013    27268  29146  silver    NY
860  Honda  Altima  2014    18563  16523  silver    FL
870  Honda   Cruze  2015    79325  37390  silver    FL
893  Honda   Camry  2017    42680  30367  silver    FL
915  Honda  Altima  2014    40254  34143  silver    FL
917  Honda   Camry  2010    70329  23971  silver    TX
939  Honda   Camry  2017    71588  17712  silver    NY
946  Honda  Altima  2018    12079  49217  silver    NY
959  Honda  Accord  2014    92005  36333  silver    TX
992  Honda  Accord  2018    20374  32248  silver    NY

In [2]:
df1=df.groupby(["year"]).agg(Total_revenue=("price", "sum"),Total_car_count=("make","count"), Average_price=("price","mean"))
df2=df1.sort_values("Average_price",ascending=False).reset_index()
df2

   year  Total_revenue  Total_car_count  Average_price
0  2012        3251543              107   30388.252336
1  2010        3855278              127   30356.519685
2  2014        3410409              113   30180.610619
3  2013        3394850              114   29779.385965
4  2017        3284445              112   29325.401786
5  2015        3080142              106   29057.943396
6  2018        3159589              110   28723.536364
7  2011        3611019              128   28211.085938
8  2016        2328947               83   28059.602410

loc snd iloc

In [ ]:
#loc -> Label based
#iloc -> Index Based

In [ ]:
len(df)

1000

In [ ]:
df.index = [i for i in range(1,1001)]

In [ ]:
df

           make   model  year  mileage  price   color state
1     Chevrolet   Cruze  2011    99157  37488   white    TX
2        Toyota   Cruze  2017    19882  34176     red    IL
3     Chevrolet  Altima  2011    77718  40297    blue    CA
4        Nissan  Fusion  2012    83613  43492  silver    TX
5          Ford   Cruze  2016    95349  26655     red    NY
...         ...     ...   ...      ...    ...     ...   ...
996       Honda  Altima  2017    25154  43139     red    FL
997   Chevrolet  Accord  2017    68264  15632   white    TX
998      Nissan   Cruze  2016    17417  30832  silver    IL
999       Honda  Accord  2011    68878  10801    blue    TX
1000  Chevrolet   Cruze  2010    99313  31827   black    CA

[1000 rows x 7 columns]

In [ ]:
df.loc[:]

           make   model  year  mileage  price   color state
1     Chevrolet   Cruze  2011    99157  37488   white    TX
2        Toyota   Cruze  2017    19882  34176     red    IL
3     Chevrolet  Altima  2011    77718  40297    blue    CA
4        Nissan  Fusion  2012    83613  43492  silver    TX
5          Ford   Cruze  2016    95349  26655     red    NY
...         ...     ...   ...      ...    ...     ...   ...
996       Honda  Altima  2017    25154  43139     red    FL
997   Chevrolet  Accord  2017    68264  15632   white    TX
998      Nissan   Cruze  2016    17417  30832  silver    IL
999       Honda  Accord  2011    68878  10801    blue    TX
1000  Chevrolet   Cruze  2010    99313  31827   black    CA

[1000 rows x 7 columns]

In [ ]:
df.loc[:,"price"]

1       37488
2       34176
3       40297
4       43492
5       26655
        ...
996     43139
997     15632
998     30832
999     10801
1000    31827
Name: price, Length: 1000, dtype: int64

In [ ]:
df.loc[:,["make","price","year"]]

           make  price  year
1     Chevrolet  37488  2011
2        Toyota  34176  2017
3     Chevrolet  40297  2011
4        Nissan  43492  2012
5          Ford  26655  2016
...         ...    ...   ...
996       Honda  43139  2017
997   Chevrolet  15632  2017
998      Nissan  30832  2016
999       Honda  10801  2011
1000  Chevrolet  31827  2010

[1000 rows x 3 columns]

In [ ]:
df.loc[1:3,["model","price","year"]]

    model  price  year
1   Cruze  37488  2011
2   Cruze  34176  2017
3  Altima  40297  2011

In [ ]:
df.loc[df["price"]>40000]
#df[df["price"]>4000]

          make   model  year  mileage  price   color state
3    Chevrolet  Altima  2011    77718  40297    blue    CA
4       Nissan  Fusion  2012    83613  43492  silver    TX
8        Honda   Cruze  2013    43679  41753     red    FL
18      Nissan   Camry  2018    78412  46579     red    TX
19      Nissan  Fusion  2011    72772  40874     red    FL
..         ...     ...   ...      ...    ...     ...   ...
988       Ford  Altima  2014    82471  44781   white    IL
989     Toyota   Camry  2013    77107  45393   white    CA
992     Toyota  Accord  2016    30406  49110    blue    IL
994  Chevrolet  Altima  2014    84439  42702  silver    IL
996      Honda  Altima  2017    25154  43139     red    FL

[230 rows x 7 columns]

In [ ]:
df.loc[df["make"]=="Toyota",["model","make","price"]]

      model    make  price
2     Cruze  Toyota  34176
6    Accord  Toyota  10359
13    Camry  Toyota  21942
14    Camry  Toyota  15233
22   Altima  Toyota  47153
..      ...     ...    ...
985   Cruze  Toyota  37810
989   Camry  Toyota  45393
990  Fusion  Toyota  37039
991   Camry  Toyota  25734
992  Accord  Toyota  49110

[206 rows x 3 columns]

**iloc**

In [ ]:
df.iloc[1:5,1:6] #slicing usg index is called iloc

    model  year  mileage  price   color
2   Cruze  2017    19882  34176     red
3  Altima  2011    77718  40297    blue
4  Fusion  2012    83613  43492  silver
5   Cruze  2016    95349  26655     red

In [ ]:
#df.loc/iloc[{row-start:stop:step},{column-start:stop:step}]

In [ ]:
df.loc[1:5, "make":"color"] #slicing usg the label is called loc

        make   model  year  mileage  price   color
1  Chevrolet   Cruze  2011    99157  37488   white
2     Toyota   Cruze  2017    19882  34176     red
3  Chevrolet  Altima  2011    77718  40297    blue
4     Nissan  Fusion  2012    83613  43492  silver
5       Ford   Cruze  2016    95349  26655     red

In [ ]:
df.loc[1:5,["model",]]

    model
1   Cruze
2   Cruze
3  Altima
4  Fusion
5   Cruze

In [ ]:
df.iloc[0]

make       Chevrolet
model          Cruze
year            2011
mileage        99157
price          37488
color          white
state             TX
Name: 1, dtype: object

In [ ]:
df.iloc[0:3]

        make   model  year  mileage  price  color state
1  Chevrolet   Cruze  2011    99157  37488  white    TX
2     Toyota   Cruze  2017    19882  34176    red    IL
3  Chevrolet  Altima  2011    77718  40297   blue    CA

In [ ]:
df.iloc[:,4]

1       37488
2       34176
3       40297
4       43492
5       26655
        ...
996     43139
997     15632
998     30832
999     10801
1000    31827
Name: price, Length: 1000, dtype: int64

In [ ]:
df.iloc[:,[0,4,2]]

           make  price  year
1     Chevrolet  37488  2011
2        Toyota  34176  2017
3     Chevrolet  40297  2011
4        Nissan  43492  2012
5          Ford  26655  2016
...         ...    ...   ...
996       Honda  43139  2017
997   Chevrolet  15632  2017
998      Nissan  30832  2016
999       Honda  10801  2011
1000  Chevrolet  31827  2010

[1000 rows x 3 columns]

In [ ]:
df.iloc[1:4,1:5]

    model  year  mileage  price
2   Cruze  2017    19882  34176
3  Altima  2011    77718  40297
4  Fusion  2012    83613  43492

In [ ]:
df.iloc[2,3] = 100000 #update the value in the table
df.head()

        make   model  year  mileage  price   color state
1  Chevrolet   Cruze  2011    99157  37488   white    TX
2     Toyota   Cruze  2017    19882  34176     red    IL
3  Chevrolet  Altima  2011   100000  40297    blue    CA
4     Nissan  Fusion  2012    83613  43492  silver    TX
5       Ford   Cruze  2016    95349  26655     red    NY

In [ ]:
df.loc[3,"mileage"] = 1000101
df.head()

        make   model  year  mileage  price   color state
1  Chevrolet   Cruze  2011    99157  37488   white    TX
2     Toyota   Cruze  2017    19882  34176     red    IL
3  Chevrolet  Altima  2011  1000101  40297    blue    CA
4     Nissan  Fusion  2012    83613  43492  silver    TX
5       Ford   Cruze  2016    95349  26655     red    NY

In [ ]:
df.loc[(df["color"]=="white") & (df["make"]=="Chevrolet"),["color"]] = "Pearl White"

In [ ]:
df

           make   model  year  mileage  price        color state
1     Chevrolet   Cruze  2011    99157  37488  Pearl White    TX
2        Toyota   Cruze  2017    19882  34176          red    IL
3     Chevrolet  Altima  2011  1000101  40297         blue    CA
4        Nissan  Fusion  2012    83613  43492       silver    TX
5          Ford   Cruze  2016    95349  26655          red    NY
...         ...     ...   ...      ...    ...          ...   ...
996       Honda  Altima  2017    25154  43139          red    FL
997   Chevrolet  Accord  2017    68264  15632  Pearl White    TX
998      Nissan   Cruze  2016    17417  30832       silver    IL
999       Honda  Accord  2011    68878  10801         blue    TX
1000  Chevrolet   Cruze  2010    99313  31827        black    CA

[1000 rows x 7 columns]

In [ ]:
df[(df["color"]=="white") & (df["make"]=="Toyota")]

       make   model  year  mileage  price  color state
22   Toyota  Altima  2011    86857  47153  white    FL
29   Toyota   Cruze  2010    26672  21328  white    NY
53   Toyota  Fusion  2013    83539  44056  white    TX
55   Toyota  Altima  2017    34037  32689  white    NY
185  Toyota   Cruze  2012    73565  35993  white    CA
189  Toyota  Accord  2016    78195  20105  white    CA
197  Toyota  Accord  2014    17610  22362  white    FL
237  Toyota  Accord  2013    28012  19212  white    NY
268  Toyota  Altima  2018    65052  17325  white    NY
279  Toyota   Cruze  2014    77396  34897  white    FL
299  Toyota   Camry  2017    15737  11435  white    NY
321  Toyota  Accord  2012    73387  27021  white    TX
347  Toyota  Accord  2015    45721  31110  white    FL
423  Toyota  Fusion  2013    80077  23483  white    CA
437  Toyota  Accord  2012    38167  24342  white    CA
549  Toyota   Cruze  2013    42757  38837  white    TX
611  Toyota   Camry  2015    31509  45668  white    TX
682  Toyota  Fusion  2017    77362  47268  white    CA
719  Toyota   Camry  2018    82612  43827  white    NY
723  Toyota  Accord  2010    32856  27073  white    TX
747  Toyota   Cruze  2017    22225  30949  white    CA
766  Toyota   Cruze  2014    50685  14998  white    TX
850  Toyota   Camry  2015    84171  28173  white    FL
852  Toyota   Cruze  2015    65113  14382  white    NY
859  Toyota   Cruze  2018    37635  29967  white    NY
896  Toyota  Fusion  2018    86084  35769  white    IL
920  Toyota  Altima  2014    39789  23476  white    TX
929  Toyota  Fusion  2010    11108  27744  white    IL
938  Toyota  Accord  2012    64721  37830  white    TX
957  Toyota  Accord  2013    49126  11253  white    NY
989  Toyota   Camry  2013    77107  45393  white    CA

In [ ]:
df.loc[(df["color"]=="white") & (df["make"]=="Toyota"),"color"] = "Black-red"

In [ ]:
df.head(30)

         make   model  year  mileage  price        color state
1   Chevrolet   Cruze  2011    99157  37488  Pearl White    TX
2      Toyota   Cruze  2017    19882  34176          red    IL
3   Chevrolet  Altima  2011  1000101  40297         blue    CA
4      Nissan  Fusion  2012    83613  43492       silver    TX
5        Ford   Cruze  2016    95349  26655          red    NY
6      Toyota  Accord  2017    23744  10359       silver    IL
7        Ford   Camry  2012    39212  25049        white    TX
8       Honda   Cruze  2013    43679  41753          red    FL
9      Nissan  Fusion  2017    44843  14642          red    FL
10      Honda  Fusion  2014    55370  23514        white    CA
11     Nissan   Cruze  2012    33608  15420          red    CA
12      Honda   Cruze  2013    41146  27168          red    IL
13     Toyota   Camry  2012    91479  21942          red    CA
14     Toyota   Camry  2014    11826  15233       silver    FL
15     Nissan  Accord  2010    67352  33656          red    TX
16       Ford  Fusion  2015    95389  10597        black    CA
17      Honda  Altima  2015    36692  19594         blue    FL
18     Nissan   Camry  2018    78412  46579          red    TX
19     Nissan  Fusion  2011    72772  40874          red    FL
20  Chevrolet   Cruze  2015    21945  22364        black    CA
21     Nissan  Altima  2013    89404  20034       silver    FL
22     Toyota  Altima  2011    86857  47153    Black-red    FL
23      Honda   Cruze  2011    51408  46098       silver    CA
24     Nissan   Camry  2017    52698  40546        white    NY
25     Nissan  Accord  2012    65905  18361         blue    TX
26     Nissan   Camry  2011    61562  38042          red    FL
27     Nissan   Camry  2015    45506  19191         blue    NY
28     Nissan  Fusion  2018    55439  26857        black    NY
29     Toyota   Cruze  2010    26672  21328    Black-red    NY
30     Nissan   Camry  2013    88226  35412          red    TX

In [ ]:
#Rename the column "color" -> "updated color"
df.rename({"color":"updated_color","state":"state_city"},axis='columns')

           make   model  year  mileage  price updated_color state_city
1     Chevrolet   Cruze  2011    99157  37488   Pearl White         TX
2        Toyota   Cruze  2017    19882  34176           red         IL
3     Chevrolet  Altima  2011  1000101  40297          blue         CA
4        Nissan  Fusion  2012    83613  43492        silver         TX
5          Ford   Cruze  2016    95349  26655           red         NY
...         ...     ...   ...      ...    ...           ...        ...
996       Honda  Altima  2017    25154  43139           red         FL
997   Chevrolet  Accord  2017    68264  15632   Pearl White         TX
998      Nissan   Cruze  2016    17417  30832        silver         IL
999       Honda  Accord  2011    68878  10801          blue         TX
1000  Chevrolet   Cruze  2010    99313  31827         black         CA

[1000 rows x 7 columns]


Basic Exploration

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 1 to 1000
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   make     1000 non-null   object
 1   model    1000 non-null   object
 2   year     1000 non-null   int64
 3   mileage  1000 non-null   int64
 4   price    1000 non-null   int64
 5   color    1000 non-null   object
 6   state    1000 non-null   object
dtypes: int64(3), object(4)
memory usage: 94.8+ KB

In [ ]:
df.describe()

             year       mileage         price
count  1000.00000  1.000000e+03   1000.000000
mean   2013.82800  5.672044e+04  29376.222000
std       2.62856  3.902943e+04  11665.612317
min    2010.00000  1.028400e+04  10022.000000
25%    2011.00000  3.513750e+04  19071.250000
50%    2014.00000  5.573950e+04  29418.500000
75%    2016.00000  7.719375e+04  39133.500000
max    2018.00000  1.000101e+06  49998.000000

In [ ]:
df.shape

(1000, 7)

In [ ]:
df.columns

Index(['make', 'model', 'year', 'mileage', 'price', 'color', 'state'], dtype='object')

In [ ]:
df.dtypes

make       object
model      object
year        int64
mileage     int64
price       int64
color      object
state      object
dtype: object

In [ ]:
df["year"] = df["year"].astype("str")

#coverting a column into another datatype
df.dtypes

make       object
model      object
year       object
mileage     int64
price       int64
color      object
state      object
dtype: object

In [ ]:
#Joins ->

Joins -> connect two tables
inner,left,right,outer

In [ ]:
import pandas as pd

# Personal DataFrame
personal_df = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 10],
    "name": ["abi", "kumar", "sheela", "mala", "kavitha", "suraj"],
    "age": [23, 34, 43, 54, 78, 34],
    "city_id": [101, 101, 102, 103, 104, 109]
})

# Salary DataFrame
salary_df = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6, 7, 8, 9],
    "salary": [10000, 20000, 30000, 40000, 50000, 60000, 70000, 50000, 40000]
})

print("Personal DataFrame:")
print(personal_df)

print("\nSalary DataFrame:")
print(salary_df)

Personal DataFrame:
   id     name  age  city_id
0   1      abi   23      101
1   2    kumar   34      101
2   3   sheela   43      102
3   4     mala   54      103
4   5  kavitha   78      104
5  10    suraj   34      109

Salary DataFrame:
   id  salary
0   1   10000
1   2   20000
2   3   30000
3   4   40000
4   5   50000
5   6   60000
6   7   70000
7   8   50000
8   9   40000

In [ ]:
personal_df

   id     name  age  city_id
0   1      abi   23      101
1   2    kumar   34      101
2   3   sheela   43      102
3   4     mala   54      103
4   5  kavitha   78      104
5  10    suraj   34      109

In [ ]:
salary_df

   id  salary
0   1   10000
1   2   20000
2   3   30000
3   4   40000
4   5   50000
5   6   60000
6   7   70000
7   8   50000
8   9   40000

In [ ]:
#inner join
pd.merge(personal_df,salary_df,left_on = "id", right_on = "id",how = "inner")

#wxact match between 2 tables

   id     name  age  city_id  salary
0   1      abi   23      101   10000
1   2    kumar   34      101   20000
2   3   sheela   43      102   30000
3   4     mala   54      103   40000
4   5  kavitha   78      104   50000

In [ ]:
#inner join
pd.merge(personal_df,salary_df,left_on = "id" ,right_on = "id",how="left")

#exact match between 2 table

   id     name  age  city_id   salary
0   1      abi   23      101  10000.0
1   2    kumar   34      101  20000.0
2   3   sheela   43      102  30000.0
3   4     mala   54      103  40000.0
4   5  kavitha   78      104  50000.0
5  10    suraj   34      109      NaN

In [ ]:
#inner join
pd.merge(personal_df,salary_df,left_on = "id" ,right_on = "id",how="right")

#exact match between 2 table

   id     name   age  city_id  salary
0   1      abi  23.0    101.0   10000
1   2    kumar  34.0    101.0   20000
2   3   sheela  43.0    102.0   30000
3   4     mala  54.0    103.0   40000
4   5  kavitha  78.0    104.0   50000
5   6      NaN   NaN      NaN   60000
6   7      NaN   NaN      NaN   70000
7   8      NaN   NaN      NaN   50000
8   9      NaN   NaN      NaN   40000

In [ ]:
#inner join
pd.merge(personal_df,salary_df,left_on = "id" ,right_on = "id",how="outer")

#exact match between 2 table

   id     name   age  city_id   salary
0   1      abi  23.0    101.0  10000.0
1   2    kumar  34.0    101.0  20000.0
2   3   sheela  43.0    102.0  30000.0
3   4     mala  54.0    103.0  40000.0
4   5  kavitha  78.0    104.0  50000.0
5   6      NaN   NaN      NaN  60000.0
6   7      NaN   NaN      NaN  70000.0
7   8      NaN   NaN      NaN  50000.0
8   9      NaN   NaN      NaN  40000.0
9  10    suraj  34.0    109.0      NaN

In [ ]:
import pandas as pd

# Personal DataFrame
personal_df = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 10],
    "name": ["abi", "kumar", "sheela", "mala", "kavitha", "suraj"],
    "age": [23, 34, 43, 54, 78, 34],
    "city_id": [101, 101, 102, 103, 104, 109]
})

# Salary DataFrame
salary_df = pd.DataFrame({
    "Emp_id": [1, 2, 3, 4, 5, 6, 7, 8, 9],
    "salary": [10000, 20000, 30000, 40000, 50000, 60000, 70000, 50000, 40000]
})

print("Personal DataFrame:")
print(personal_df)

print("\nSalary DataFrame:")
print(salary_df)

Personal DataFrame:
   id     name  age  city_id
0   1      abi   23      101
1   2    kumar   34      101
2   3   sheela   43      102
3   4     mala   54      103
4   5  kavitha   78      104
5  10    suraj   34      109

Salary DataFrame:
   Emp_id  salary
0       1   10000
1       2   20000
2       3   30000
3       4   40000
4       5   50000
5       6   60000
6       7   70000
7       8   50000
8       9   40000

In [ ]:
#inner join
pd.merge(personal_df,salary_df,left_on = "id" ,right_on = "Emp_id",how="inner")

#exact match between 2 table

   id     name  age  city_id  Emp_id  salary
0   1      abi   23      101       1   10000
1   2    kumar   34      101       2   20000
2   3   sheela   43      102       3   30000
3   4     mala   54      103       4   40000
4   5  kavitha   78      104       5   50000

In [ ]:
#inner join
pd.merge(personal_df,salary_df,left_on = "id" ,right_on = "Emp_id",how="left")

#exact match between 2 table

   id     name  age  city_id  Emp_id   salary
0   1      abi   23      101     1.0  10000.0
1   2    kumar   34      101     2.0  20000.0
2   3   sheela   43      102     3.0  30000.0
3   4     mala   54      103     4.0  40000.0
4   5  kavitha   78      104     5.0  50000.0
5  10    suraj   34      109     NaN      NaN

In [ ]:
#inner join
pd.merge(personal_df,salary_df,left_on = "id" ,right_on = "Emp_id",how="right")

#exact match between 2 table

    id     name   age  city_id  Emp_id  salary
0  1.0      abi  23.0    101.0       1   10000
1  2.0    kumar  34.0    101.0       2   20000
2  3.0   sheela  43.0    102.0       3   30000
3  4.0     mala  54.0    103.0       4   40000
4  5.0  kavitha  78.0    104.0       5   50000
5  NaN      NaN   NaN      NaN       6   60000
6  NaN      NaN   NaN      NaN       7   70000
7  NaN      NaN   NaN      NaN       8   50000
8  NaN      NaN   NaN      NaN       9   40000

In [ ]:
#outer join
pd.merge(personal_df,salary_df,left_on = "id" ,right_on = "Emp_id",how="outer")

#exact match between 2 table

     id     name   age  city_id  Emp_id   salary
0   1.0      abi  23.0    101.0     1.0  10000.0
1   2.0    kumar  34.0    101.0     2.0  20000.0
2   3.0   sheela  43.0    102.0     3.0  30000.0
3   4.0     mala  54.0    103.0     4.0  40000.0
4   5.0  kavitha  78.0    104.0     5.0  50000.0
5   NaN      NaN   NaN      NaN     6.0  60000.0
6   NaN      NaN   NaN      NaN     7.0  70000.0
7   NaN      NaN   NaN      NaN     8.0  50000.0
8   NaN      NaN   NaN      NaN     9.0  40000.0
9  10.0    suraj  34.0    109.0     NaN      NaN

Rank

In [ ]:
#creating and applying for price -> descending
df["rank"] =df["price"].rank(ascending = False) #descending order
df3 = df[df["rank"]<=15]
df3

          make   model  year  mileage  price   color state  rank
249     Nissan  Altima  2012    17511  49787   black    NY   9.0
272      Honda  Fusion  2014    81328  49920     red    CA   4.0
276      Honda   Camry  2015    18206  49971  silver    CA   3.0
278       Ford   Cruze  2017    68806  49907  silver    CA   5.0
461     Toyota   Camry  2014    25844  49871     red    IL   8.0
513     Nissan  Altima  2017    68580  49781    blue    FL  10.0
555       Ford   Camry  2013    20731  49875  silver    IL   7.0
582  Chevrolet  Accord  2015    51768  49464   black    IL  14.0
636  Chevrolet  Accord  2011    14481  49998     red    FL   1.0
676     Toyota  Fusion  2014    25925  49763     red    FL  12.0
772      Honda  Altima  2015    87021  49424     red    IL  15.0
883       Ford  Altima  2011    49827  49768    blue    FL  11.0
887     Toyota   Cruze  2014    38847  49473     red    NY  13.0
955     Nissan   Camry  2010    12725  49989     red    TX   2.0
963     Nissan   Camry  2010    13245  49884    blue    NY   6.0

In [ ]:
df3.sort_values("rank", ascending=True)

          make   model  year  mileage  price   color state  rank
636  Chevrolet  Accord  2011    14481  49998     red    FL   1.0
955     Nissan   Camry  2010    12725  49989     red    TX   2.0
276      Honda   Camry  2015    18206  49971  silver    CA   3.0
272      Honda  Fusion  2014    81328  49920     red    CA   4.0
278       Ford   Cruze  2017    68806  49907  silver    CA   5.0
963     Nissan   Camry  2010    13245  49884    blue    NY   6.0
555       Ford   Camry  2013    20731  49875  silver    IL   7.0
461     Toyota   Camry  2014    25844  49871     red    IL   8.0
249     Nissan  Altima  2012    17511  49787   black    NY   9.0
513     Nissan  Altima  2017    68580  49781    blue    FL  10.0
883       Ford  Altima  2011    49827  49768    blue    FL  11.0
676     Toyota  Fusion  2014    25925  49763     red    FL  12.0
887     Toyota   Cruze  2014    38847  49473     red    NY  13.0
582  Chevrolet  Accord  2015    51768  49464   black    IL  14.0
772      Honda  Altima  2015    87021  49424     red    IL  15.0

Date_columns

In [ ]:
import pandas as pd

sheet_id = "1RVnUAGVsr4lrt7nZ2WOq2hFkj7gFcRef"
sheet_name = "Orders"  # or the visible tab name

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
df = pd.read_csv(url)

df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,01-21-2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,02-26-2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,02-26-2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,02-26-2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,05-04-2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
#df.astype("object")

#need to convert this column datatype as data
df["Order Date"]=pd.to_datetime(df["Order Date"])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9983 non-null   float64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(14)
memory usage: 1.6+ MB

In [ ]:
df["year"]=df["Order Date"].dt.year
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,year
0,1,CA-2016-152156,2016-11-08,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016
1,2,CA-2016-152156,2016-11-08,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016
2,3,CA-2016-138688,2016-06-12,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016
3,4,US-2015-108966,2015-10-11,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015
4,5,US-2015-108966,2015-10-11,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,2014
9990,9991,CA-2017-121258,2017-02-26,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,2017
9991,9992,CA-2017-121258,2017-02-26,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,2017
9992,9993,CA-2017-121258,2017-02-26,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,2017
9993,9994,CA-2017-119914,2017-05-04,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,2017

In [ ]:
df["Order Date"].dt.month

0       11
1       11
2        6
3       10
4       10
        ..
9989     1
9990     2
9991     2
9992     2
9993     5
Name: Order Date, Length: 9994, dtype: int32

In [ ]:
df["Order Date"].dt.day

0        8
1        8
2       12
3       11
4       11
        ..
9989    21
9990    26
9991    26
9992    26
9993     4
Name: Order Date, Length: 9994, dtype: int32

In [ ]:
df["Order Date"].dt.day_name()

0        Tuesday
1        Tuesday
2         Sunday
3         Sunday
4         Sunday
          ...
9989     Tuesday
9990      Sunday
9991      Sunday
9992      Sunday
9993    Thursday
Name: Order Date, Length: 9994, dtype: object

In [ ]:
df["Order Date"].dt.month_name()

0       November
1       November
2           June
3        October
4        October
          ...
9989     January
9990    February
9991    February
9992    February
9993         May
Name: Order Date, Length: 9994, dtype: object

In [ ]:
!pip install kagglehub[pandas-datasets]

Requirement already satisfied: kagglehub[pandas-datasets] in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (25.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (4.67.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2025.11.12)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)

In [ ]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]

import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the file path (CSV inside the dataset)
file_path = "HRDataset_v14.csv"

# Load the latest version of the dataset
df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "rhuebner/human-resources-data-set",
    file_path
)

print("First 5 records:")
print(df.head())

/tmp/ipython-input-3647318895.py:11: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading from https://www.kaggle.com/api/v1/datasets/download/rhuebner/human-resources-data-set?dataset_version_number=4&file_name=HRDataset_v14.csv...

100%|██████████| 75.1k/75.1k [00:00<00:00, 1.37MB/s]

First 5 records:
              Employee_Name  EmpID  MarriedID  MaritalStatusID  GenderID  \
0       Adinolfi, Wilson  K  10026          0                0         1
1  Ait Sidi, Karthikeyan     10084          1                1         1
2         Akinkuolie, Sarah  10196          1                1         0
3              Alagbe,Trina  10088          1                1         0
4          Anderson, Carol   10069          0                2         0

   EmpStatusID  DeptID  PerfScoreID  FromDiversityJobFairID  Salary  ...  \
0            1       5            4                       0   62506  ...
1            5       3            3                       0  104437  ...
2            5       5            3                       0   64955  ...
3            1       5            3                       0   64991  ...
4            5       5            3                       0   50825  ...

      ManagerName  ManagerID RecruitmentSource PerformanceScore  \
0  Michael Albert       22.0          LinkedIn          Exceeds
1      Simon Roup        4.0            Indeed      Fully Meets
2  Kissy Sullivan       20.0          LinkedIn      Fully Meets
3    Elijiah Gray       16.0            Indeed      Fully Meets
4  Webster Butler       39.0     Google Search      Fully Meets

   EngagementSurvey EmpSatisfaction SpecialProjectsCount  \
0              4.60               5                    0
1              4.96               3                    6
2              3.02               3                    0
3              4.84               5                    0
4              5.00               4                    0

  LastPerformanceReview_Date DaysLateLast30 Absences
0                  1/17/2019              0        1
1                  2/24/2016              0       17
2                  5/15/2012              0        3
3                   1/3/2019              0       15
4                   2/1/2016              0        2

[5 rows x 36 columns]

In [ ]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
307,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

Warning: Total number of columns (36) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    object
 16  Sex                         311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   303 non-null    float64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    object
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 87.6+ KB

In [ ]:
#which source people recruitmenthires - more hire

In [ ]:
df1 = df.groupby(["RecruitmentSource"]).agg(Total_by_sources=("RecruitmentSource","count"))
df1["rank"] = df1["Total_by_sources"].rank(ascending=False)
df1.sort_values("rank", ascending=True).reset_index().head(3)

  RecruitmentSource  Total_by_sources  rank
0            Indeed                87   1.0
1          LinkedIn                76   2.0
2     Google Search                49   3.0

In [ ]:
df1=df.groupby(["RecruitmentSource"]).agg(Total_Recruit_Source=("RecruitmentSource","count"))
df1.sort_values('Total_Recruit_Source', ascending=False).reset_index()

df1["rank"] = df1["Total_Recruit_Source"].rank(ascending=False) #descending order
df1[df1["rank"]<=5].sort_values('rank',ascending=True)

                    Total_Recruit_Source  rank
RecruitmentSource
Indeed                                87   1.0
LinkedIn                              76   2.0
Google Search                         49   3.0
Employee Referral                     31   4.0
Diversity Job Fair                    29   5.0

In [ ]:
#which source (RecruitmentSource) - more people hired
df1 = df.groupby("RecruitmentSource").agg(Total_count=("RecruitmentSource","count")).reset_index()
df1["Percentage"] = round(df1["Total_count"]/len(df)*100,2)
df1.sort_values("Total_count",ascending=False)

#inference => Iam choosing the indeed subscription it is 28%

         RecruitmentSource  Total_count  Percentage
4                   Indeed           87       27.97
5                 LinkedIn           76       24.44
3            Google Search           49       15.76
2        Employee Referral           31        9.97
1       Diversity Job Fair           29        9.32
0            CareerBuilder           23        7.40
8                  Website           13        4.18
7                    Other            2        0.64
6  On-line Web application            1        0.32

In [ ]:
#year over hiring rate

In [ ]:
df["Date"]=pd.to_datetime(df["DateofHire"]) #
df["year"]=df["Date"].dt.year
df1 = df.groupby("year").agg(Total_hire=("year","count")).reset_index()

df1.sort_values("Total_hire",ascending=False)

    year  Total_hire
5   2011          83
8   2014          60
6   2012          45
7   2013          44
9   2015          36
10  2016          14
4   2010           9
3   2009           7
11  2017           6
2   2008           3
1   2007           2
0   2006           1
12  2018           1

In [ ]:
#average salary of each department
#department wise people count who is receiving salary then above average
#

In [ ]:
df["Department"].unique()

array(['Production       ', 'IT/IS', 'Software Engineering',
       'Admin Offices', 'Sales', 'Executive Office'], dtype=object)

In [ ]:
df.loc[df["Department"]=="Production       ","Department"] = "Production"

In [ ]:
df["Department"].unique()

array(['Production', 'IT/IS', 'Software Engineering', 'Admin Offices',
       'Sales', 'Executive Office'], dtype=object)

In [ ]:
#production
#IT/ITS

In [ ]:
#average salary of each department
df1 = df.groupby("Department").agg(avg_salary=("Salary","mean")).reset_index()
df1.sort_values("avg_salary",ascending=False)

             Department     avg_salary
1      Executive Office  250000.000000
2                 IT/IS   97064.640000
5  Software Engineering   94989.454545
0         Admin Offices   71791.888889
4                 Sales   69061.258065
3            Production   59953.545455

In [ ]:
df1  = df.groupby("Department").agg(Average_salary = ("Salary","mean")).reset_index()
df1

             Department  Average_salary
0         Admin Offices    71791.888889
1      Executive Office   250000.000000
2                 IT/IS    97064.640000
3            Production    59953.545455
4                 Sales    69061.258065
5  Software Engineering    94989.454545

In [ ]:
#department wise people count who is receiving salary then above average
df2 = pd.merge(df,df1,left_on ="Department",right_on="Department",how="left")

df2.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,Date,year,Average_salary
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Exceeds,4.60,5,0,1/17/2019,0,1,2011-07-05,2011,59953.545455
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Fully Meets,4.96,3,6,2/24/2016,0,17,2015-03-30,2015,97064.640000
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Fully Meets,3.02,3,0,5/15/2012,0,3,2011-07-05,2011,59953.545455
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Fully Meets,4.84,5,0,1/3/2019,0,15,2008-01-07,2008,59953.545455
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,2011-07-11,2011,59953.545455

In [ ]:
df3 = df2[df2["Salary"] > df2["Average_salary"]]

In [ ]:
df3.groupby("Department").agg(Average_salary = ("Department","count")).reset_index()

             Department  Average_salary
0         Admin Offices               3
1                 IT/IS              19
2            Production             102
3                 Sales              10
4  Software Engineering               6