In [5]:
#inbuilt libraries
# we want handle data-> handle data

In [4]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd #like call pandas as pd
#pd => handle,clean,

In [2]:
# 1 dim => series
# 2 dim => Data frame

a = [1,2,3,4,5,6,7,8,9,10]
type(a)

list

In [6]:
pd.Series(a)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
type(pd.Series(a))

pandas.core.series.Series

In [ ]:
data = {'Subject': ['Maths', 'History', 'Science', 'English', 'Georaphy', 'Art'],
        'Marks': (45, 65, 78, 65, 80, 78),
        'GPA': [2.5, 3.0, 3.5, 2.0, 4.0, 4.0]}
pd.Series(data)

Subject    [Maths, History, Science, English, Georaphy, Art]
Marks                               (45, 65, 78, 65, 80, 78)
GPA                           [2.5, 3.0, 3.5, 2.0, 4.0, 4.0]
dtype: object

In [ ]:
data = {'Subject': ['Maths', 'History', 'Science', 'English', 'Georaphy', 'Art'],
        'Marks': (45, 65, 78, 65, 80, 78),
        'GPA': [2.5, 3.0, 3.5, 2.0, 4.0, 4.0]}
pd.DataFrame(data)

    Subject  Marks  GPA
0     Maths     45  2.5
1   History     65  3.0
2   Science     78  3.5
3   English     65  2.0
4  Georaphy     80  4.0
5       Art     78  4.0

In [ ]:
#csv, xlsx, tsv, json
#all file formats
pd.read_excel("/content/Sample - Superstore.xlsx")

df = pd.read_excel("/content/Sample - Superstore.xlsx")
print(df.head())

   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045
3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335
4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

In [ ]:
import pandas as pd

sheet_id = "1RVnUAGVsr4lrt7nZ2WOq2hFkj7gFcRef"
sheet_name = "Orders"  # or the visible tab name

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
df = pd.read_csv(url)

print(df.head())

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156   8/11/2016  11/11/2016    Second Class    CG-12520
1       2  CA-2016-152156   8/11/2016  11/11/2016    Second Class    CG-12520
2       3  CA-2016-138688   12/6/2016   16/6/2016    Second Class    DV-13045
3       4  US-2015-108966  11/10/2015  18/10/2015  Standard Class    SO-20335
4       5  US-2015-108966  11/10/2015  18/10/2015  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0     42420.0   South  FUR-BO-10001798        Furniture    Bookcases
1     42420.0   South  FUR-CH-10000454        Furniture       Chairs
2     90036.0    West  OFF-LA-10000240  Office Supplies       Labels
3     33311.0   South  FUR-TA-10000577        Furniture       Tables
4     33311.0   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

In [7]:
import pandas as pd

sheet_id = "1MvO7bmVEjlu3EOY_lxDrwQjQ0dBeH97gHkOL6aYBxJc"
sheet_name = "Sheet1"  # change if ur tab name is different

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
df = pd.read_csv(url)

df

          make   model  year  mileage  price   color state
0    Chevrolet   Cruze  2011    99157  37488   white    TX
1       Toyota   Cruze  2017    19882  34176     red    IL
2    Chevrolet  Altima  2011    77718  40297    blue    CA
3       Nissan  Fusion  2012    83613  43492  silver    TX
4         Ford   Cruze  2016    95349  26655     red    NY
..         ...     ...   ...      ...    ...     ...   ...
995      Honda  Altima  2017    25154  43139     red    FL
996  Chevrolet  Accord  2017    68264  15632   white    TX
997     Nissan   Cruze  2016    17417  30832  silver    IL
998      Honda  Accord  2011    68878  10801    blue    TX
999  Chevrolet   Cruze  2010    99313  31827   black    CA

[1000 rows x 7 columns]

In [ ]:
#select the column
#filtering the data
#sorting the data
df.head() #First 5 Records

        make   model  year  mileage  price   color state
0  Chevrolet   Cruze  2011    99157  37488   white    TX
1     Toyota   Cruze  2017    19882  34176     red    IL
2  Chevrolet  Altima  2011    77718  40297    blue    CA
3     Nissan  Fusion  2012    83613  43492  silver    TX
4       Ford   Cruze  2016    95349  26655     red    NY

In [ ]:
df.head(10) #no, of rows will display

        make   model  year  mileage  price   color state
0  Chevrolet   Cruze  2011    99157  37488   white    TX
1     Toyota   Cruze  2017    19882  34176     red    IL
2  Chevrolet  Altima  2011    77718  40297    blue    CA
3     Nissan  Fusion  2012    83613  43492  silver    TX
4       Ford   Cruze  2016    95349  26655     red    NY
5     Toyota  Accord  2017    23744  10359  silver    IL
6       Ford   Camry  2012    39212  25049   white    TX
7      Honda   Cruze  2013    43679  41753     red    FL
8     Nissan  Fusion  2017    44843  14642     red    FL
9      Honda  Fusion  2014    55370  23514   white    CA

In [8]:
df.tail() #Last 5 Records

          make   model  year  mileage  price   color state
995      Honda  Altima  2017    25154  43139     red    FL
996  Chevrolet  Accord  2017    68264  15632   white    TX
997     Nissan   Cruze  2016    17417  30832  silver    IL
998      Honda  Accord  2011    68878  10801    blue    TX
999  Chevrolet   Cruze  2010    99313  31827   black    CA

In [ ]:
df["price"]

print(df["make"])

0      Chevrolet
1         Toyota
2      Chevrolet
3         Nissan
4           Ford
         ...
995        Honda
996    Chevrolet
997       Nissan
998        Honda
999    Chevrolet
Name: make, Length: 1000, dtype: object

In [ ]:
df[["make","price","mileage"]]#this more than 1 dimension => 2d we use [[ ]]

          make  price  mileage
0    Chevrolet  37488    99157
1       Toyota  34176    19882
2    Chevrolet  40297    77718
3       Nissan  43492    83613
4         Ford  26655    95349
..         ...    ...      ...
995      Honda  43139    25154
996  Chevrolet  15632    68264
997     Nissan  30832    17417
998      Honda  10801    68878
999  Chevrolet  31827    99313

[1000 rows x 3 columns]

In [ ]:
df[["price","mileage"]].head()

   price  mileage
0  37488    99157
1  34176    19882
2  40297    77718
3  43492    83613
4  26655    95349

In [ ]:
# filter
#year > 2016
df[df["year"] > 2016] #df(complete _data){True/False}

          make   model  year  mileage  price   color state
1       Toyota   Cruze  2017    19882  34176     red    IL
5       Toyota  Accord  2017    23744  10359  silver    IL
8       Nissan  Fusion  2017    44843  14642     red    FL
17      Nissan   Camry  2018    78412  46579     red    TX
23      Nissan   Camry  2017    52698  40546   white    NY
..         ...     ...   ...      ...    ...     ...   ...
986  Chevrolet  Accord  2018    47264  12039     red    CA
992      Honda  Accord  2018    20374  32248  silver    NY
994  Chevrolet  Accord  2018    26933  21813  silver    TX
995      Honda  Altima  2017    25154  43139     red    FL
996  Chevrolet  Accord  2017    68264  15632   white    TX

[222 rows x 7 columns]

In [ ]:
df[df["price"]>42000]

          make   model  year  mileage  price   color state
3       Nissan  Fusion  2012    83613  43492  silver    TX
17      Nissan   Camry  2018    78412  46579     red    TX
21      Toyota  Altima  2011    86857  47153   white    FL
22       Honda   Cruze  2011    51408  46098  silver    CA
34      Toyota   Cruze  2010    59107  42947     red    FL
..         ...     ...   ...      ...    ...     ...   ...
987       Ford  Altima  2014    82471  44781   white    IL
988     Toyota   Camry  2013    77107  45393   white    CA
991     Toyota  Accord  2016    30406  49110    blue    IL
993  Chevrolet  Altima  2014    84439  42702  silver    IL
995      Honda  Altima  2017    25154  43139     red    FL

[180 rows x 7 columns]

In [ ]:
#and/or

#red color cars with pricw > 4000
df[(df["color"]=="red") & (df["price"]>4000)]

          make   model  year  mileage  price color state
1       Toyota   Cruze  2017    19882  34176   red    IL
4         Ford   Cruze  2016    95349  26655   red    NY
7        Honda   Cruze  2013    43679  41753   red    FL
8       Nissan  Fusion  2017    44843  14642   red    FL
10      Nissan   Cruze  2012    33608  15420   red    CA
..         ...     ...   ...      ...    ...   ...   ...
964     Toyota   Camry  2012    59101  28453   red    TX
967  Chevrolet  Altima  2010    46134  44521   red    TX
978      Honda  Fusion  2013    46262  44387   red    IL
986  Chevrolet  Accord  2018    47264  12039   red    CA
995      Honda  Altima  2017    25154  43139   red    FL

[205 rows x 7 columns]

In [ ]:
#and/or

#red color cars with pricw > 4000
df[(df["color"]=="red") | (df["price"]>4000)] #| = or

          make   model  year  mileage  price   color state
0    Chevrolet   Cruze  2011    99157  37488   white    TX
1       Toyota   Cruze  2017    19882  34176     red    IL
2    Chevrolet  Altima  2011    77718  40297    blue    CA
3       Nissan  Fusion  2012    83613  43492  silver    TX
4         Ford   Cruze  2016    95349  26655     red    NY
..         ...     ...   ...      ...    ...     ...   ...
995      Honda  Altima  2017    25154  43139     red    FL
996  Chevrolet  Accord  2017    68264  15632   white    TX
997     Nissan   Cruze  2016    17417  30832  silver    IL
998      Honda  Accord  2011    68878  10801    blue    TX
999  Chevrolet   Cruze  2010    99313  31827   black    CA

[1000 rows x 7 columns]

In [ ]:
#Filter all cars where price is greater than 42000.

#Display cars that were manufactured after the year 2015 in Honda.

#Select all cars with mileage less than 60000 for the model Fusion.

#Filter the dataset to show only cars where color is "White".

#Display all cars that are available in the state "CA" and color is silver.

In [ ]:
print(df[df["price"]>42000])

          make   model  year  mileage  price   color state
3       Nissan  Fusion  2012    83613  43492  silver    TX
17      Nissan   Camry  2018    78412  46579     red    TX
21      Toyota  Altima  2011    86857  47153   white    FL
22       Honda   Cruze  2011    51408  46098  silver    CA
34      Toyota   Cruze  2010    59107  42947     red    FL
..         ...     ...   ...      ...    ...     ...   ...
987       Ford  Altima  2014    82471  44781   white    IL
988     Toyota   Camry  2013    77107  45393   white    CA
991     Toyota  Accord  2016    30406  49110    blue    IL
993  Chevrolet  Altima  2014    84439  42702  silver    IL
995      Honda  Altima  2017    25154  43139     red    FL

[180 rows x 7 columns]

In [ ]:
df[(df["make"] == "Honda") & (df["year"] > 2015)]

      make   model  year  mileage  price   color state
30   Honda   Camry  2016    12078  22661  silver    FL
60   Honda   Cruze  2018    63917  47289     red    TX
87   Honda  Accord  2016    35405  26922   white    IL
102  Honda  Altima  2017    88529  38257    blue    TX
103  Honda   Cruze  2018    77840  35296   white    TX
134  Honda   Camry  2018    93813  14436  silver    TX
165  Honda   Camry  2018    23531  13192   white    IL
169  Honda  Accord  2016    93871  48770    blue    NY
181  Honda  Fusion  2018    72574  10032    blue    NY
197  Honda  Altima  2017    74772  48787   white    NY
224  Honda  Accord  2017    66330  27324     red    FL
254  Honda   Cruze  2018    14870  30989   black    TX
343  Honda   Cruze  2017    58173  36523   white    CA
349  Honda  Accord  2016    81176  24038   white    IL
388  Honda  Accord  2017    58552  29308   black    CA
416  Honda  Fusion  2017    33834  23886  silver    CA
428  Honda  Accord  2018    36610  24300     red    TX
461  Honda   Cruze  2016    85494  16471   black    FL
466  Honda  Fusion  2017    36557  26337    blue    FL
479  Honda  Accord  2018    24083  12852   white    IL
491  Honda  Fusion  2018    90218  29560   white    FL
528  Honda  Altima  2017    69823  14480   white    CA
531  Honda  Altima  2018    51026  29581   white    FL
532  Honda   Camry  2018    60743  40380    blue    TX
533  Honda  Accord  2018    13677  29954     red    IL
546  Honda  Fusion  2018    16069  24439  silver    CA
547  Honda   Cruze  2017    89704  40498     red    TX
561  Honda  Accord  2017    18722  45798  silver    TX
598  Honda  Fusion  2016    59068  14314     red    NY
599  Honda  Accord  2018    76692  24581     red    IL
612  Honda  Accord  2017    71930  37752   white    CA
620  Honda   Cruze  2017    22650  21426     red    CA
645  Honda   Camry  2018    99367  11520    blue    FL
657  Honda   Camry  2016    77970  13406     red    TX
659  Honda   Camry  2017    43095  45353  silver    CA
661  Honda  Accord  2018    30430  45372   black    NY
685  Honda  Altima  2016    14572  29932   black    TX
713  Honda   Cruze  2016    54801  17990  silver    FL
730  Honda  Fusion  2017    82367  27958   black    NY
734  Honda  Altima  2017    51565  27113   black    FL
749  Honda   Cruze  2017    87423  47348  silver    NY
790  Honda  Altima  2018    38019  16844   black    TX
799  Honda  Fusion  2016    55635  15289  silver    CA
833  Honda  Accord  2016    90679  21621  silver    FL
837  Honda  Accord  2017    54386  12271  silver    TX
866  Honda  Altima  2018    65777  40998     red    TX
876  Honda   Cruze  2017    19474  26400    blue    NY
893  Honda   Camry  2017    42680  30367  silver    FL
916  Honda  Accord  2018    35269  13976   white    TX
939  Honda   Camry  2017    71588  17712  silver    NY
946  Honda  Altima  2018    12079  49217  silver    NY
952  Honda   Cruze  2018    54761  29466     red    FL
992  Honda  Accord  2018    20374  32248  silver    NY
995  Honda  Altima  2017    25154  43139     red    FL

In [ ]:
df[(df["mileage"]<60000) & (df["make"]== "Honda") & (df["model"]== "Fusion")]

      make   model  year  mileage  price   color state
9    Honda  Fusion  2014    55370  23514   white    CA
32   Honda  Fusion  2013    32028  19385   white    CA
235  Honda  Fusion  2010    59729  38162   black    NY
240  Honda  Fusion  2014    51983  22739     red    CA
258  Honda  Fusion  2014    44794  10135   white    NY
285  Honda  Fusion  2013    22030  45530   white    IL
303  Honda  Fusion  2015    16957  37880    blue    NY
371  Honda  Fusion  2014    43764  34087   black    TX
416  Honda  Fusion  2017    33834  23886  silver    CA
457  Honda  Fusion  2010    37641  31169    blue    FL
466  Honda  Fusion  2017    36557  26337    blue    FL
506  Honda  Fusion  2015    50841  14419  silver    NY
544  Honda  Fusion  2013    25360  38818    blue    IL
546  Honda  Fusion  2018    16069  24439  silver    CA
549  Honda  Fusion  2010    56055  49053   black    TX
569  Honda  Fusion  2013    42349  17475   black    IL
598  Honda  Fusion  2016    59068  14314     red    NY
799  Honda  Fusion  2016    55635  15289  silver    CA
933  Honda  Fusion  2014    58183  12447   white    NY
978  Honda  Fusion  2013    46262  44387     red    IL

In [ ]:
df[df["color"] == "white"]

          make   model  year  mileage  price  color state
0    Chevrolet   Cruze  2011    99157  37488  white    TX
6         Ford   Camry  2012    39212  25049  white    TX
9        Honda  Fusion  2014    55370  23514  white    CA
21      Toyota  Altima  2011    86857  47153  white    FL
23      Nissan   Camry  2017    52698  40546  white    NY
..         ...     ...   ...      ...    ...    ...   ...
975      Honda   Cruze  2011    48055  12302  white    NY
982     Nissan  Fusion  2018    30045  10818  white    NY
987       Ford  Altima  2014    82471  44781  white    IL
988     Toyota   Camry  2013    77107  45393  white    CA
996  Chevrolet  Accord  2017    68264  15632  white    TX

[194 rows x 7 columns]

In [ ]:
df[(df["state"] == "CA") & (df["color"] == "silver")]

          make   model  year  mileage  price   color state
22       Honda   Cruze  2011    51408  46098  silver    CA
70        Ford  Fusion  2014    33947  37357  silver    CA
99      Nissan   Camry  2011    48230  30697  silver    CA
111       Ford  Fusion  2014    45074  23006  silver    CA
118      Honda   Cruze  2015    80746  13727  silver    CA
121     Nissan   Camry  2012    97730  42837  silver    CA
153     Nissan  Accord  2017    56042  25695  silver    CA
193  Chevrolet  Fusion  2015    77641  31940  silver    CA
212       Ford  Altima  2012    17547  47126  silver    CA
223  Chevrolet  Altima  2017    33598  29734  silver    CA
275      Honda   Camry  2015    18206  49971  silver    CA
277       Ford   Cruze  2017    68806  49907  silver    CA
313  Chevrolet  Fusion  2017    64879  43126  silver    CA
335  Chevrolet   Cruze  2012    27076  13663  silver    CA
373       Ford  Accord  2013    76917  42116  silver    CA
406  Chevrolet  Accord  2013    45487  46341  silver    CA
414  Chevrolet   Cruze  2012    49033  32056  silver    CA
416      Honda  Fusion  2017    33834  23886  silver    CA
449      Honda   Cruze  2015    46781  10972  silver    CA
455     Nissan   Camry  2014    60612  27264  silver    CA
465       Ford  Altima  2015    89447  22548  silver    CA
496       Ford   Camry  2014    40278  12861  silver    CA
519     Nissan   Camry  2010    94789  10672  silver    CA
524      Honda   Cruze  2011    96442  46996  silver    CA
525     Toyota  Accord  2011    58468  14328  silver    CA
546      Honda  Fusion  2018    16069  24439  silver    CA
550  Chevrolet   Cruze  2011    91582  47689  silver    CA
595       Ford  Accord  2012    72705  27587  silver    CA
654     Toyota   Camry  2010    13941  18722  silver    CA
659      Honda   Camry  2017    43095  45353  silver    CA
689     Toyota  Fusion  2014    54387  39628  silver    CA
712      Honda   Camry  2013    90392  28391  silver    CA
752     Toyota  Altima  2010    64316  45297  silver    CA
775     Nissan  Altima  2011    89965  10776  silver    CA
791     Nissan  Fusion  2014    83120  23611  silver    CA
793  Chevrolet   Camry  2015    49539  20015  silver    CA
799      Honda  Fusion  2016    55635  15289  silver    CA
811      Honda   Camry  2011    55769  19553  silver    CA
818  Chevrolet   Cruze  2015    29359  46739  silver    CA
823       Ford   Cruze  2017    89454  21249  silver    CA
902       Ford  Fusion  2016    41013  20559  silver    CA
909  Chevrolet   Camry  2017    95067  11847  silver    CA
943     Nissan   Cruze  2010    19018  31801  silver    CA
977  Chevrolet  Fusion  2016    11007  10037  silver    CA
983       Ford   Camry  2013    44049  47437  silver    CA

In [ ]:
#sorting
print(df.sort_values("price", ascending= True))

#sort_values -> used to sort the data
#columns inside
#ascending = True----->Ascending order
#ascending = False-------->Descending order

          make   model  year  mileage  price   color state
336     Toyota   Cruze  2015    13455  10022  silver    IL
181      Honda  Fusion  2018    72574  10032    blue    NY
977  Chevrolet  Fusion  2016    11007  10037  silver    CA
572     Toyota   Camry  2014    19779  10039    blue    CA
754     Nissan  Altima  2017    25716  10091     red    TX
..         ...     ...   ...      ...    ...     ...   ...
277       Ford   Cruze  2017    68806  49907  silver    CA
271      Honda  Fusion  2014    81328  49920     red    CA
275      Honda   Camry  2015    18206  49971  silver    CA
954     Nissan   Camry  2010    12725  49989     red    TX
635  Chevrolet  Accord  2011    14481  49998     red    FL

[1000 rows x 7 columns]

In [ ]:
df.sort_values(["year","price"], ascending=[True, False])
#sorting 2 columns
#year -> asc
#price -> desc

       make   model  year  mileage  price  color state
954  Nissan   Camry  2010    12725  49989    red    TX
962  Nissan   Camry  2010    13245  49884   blue    NY
853  Nissan   Camry  2010    23681  49199  black    CA
549   Honda  Fusion  2010    56055  49053  black    TX
884    Ford  Accord  2010    92134  48926  black    FL
..      ...     ...   ...      ...    ...    ...   ...
819  Nissan   Cruze  2018    47336  11769  black    TX
645   Honda   Camry  2018    99367  11520   blue    FL
982  Nissan  Fusion  2018    30045  10818  white    NY
924  Nissan  Fusion  2018    57005  10631    red    CA
181   Honda  Fusion  2018    72574  10032   blue    NY

[1000 rows x 7 columns]

In [ ]:
df[df['color']=='silver'].sort_values('price',ascending =True)[["make","model","price"]]
#sort_values -> used to sort the data
#columns inside
#ascending = True --> Ascending Order
#ascending = False --> Descending Order

          make   model  price
336     Toyota   Cruze  10022
977  Chevrolet  Fusion  10037
5       Toyota  Accord  10359
684       Ford  Altima  10539
519     Nissan   Camry  10672
..         ...     ...    ...
715      Honda  Accord  48900
946      Honda  Altima  49217
554       Ford   Camry  49875
277       Ford   Cruze  49907
275      Honda   Camry  49971

[219 rows x 3 columns]

In [ ]:
# Filter cars where price is greater than 500000 AND year is after 2016.now sort it by price desc.


# Display cars where color is "White" OR state is "CA".

# Filter cars with mileage less than 70000 AND price below 800000.

# Select only the columns make, model, and price for cars manufactured after 2018.

# Sort the cars by price in descending order and display only the top 10 rows.

In [ ]:
df[(df['price'] > 5000) & (df["year"] > 2016)].sort_values("price", ascending = False)

       make   model  year  mileage  price   color state
277    Ford   Cruze  2017    68806  49907  silver    CA
512  Nissan  Altima  2017    68580  49781    blue    FL
682    Ford  Fusion  2018    71010  49401    blue    TX
796    Ford  Accord  2017    65746  49242   white    FL
946   Honda  Altima  2018    12079  49217  silver    NY
..      ...     ...   ...      ...    ...     ...   ...
366    Ford  Accord  2017    70597  10697   white    IL
924  Nissan  Fusion  2018    57005  10631     red    CA
5    Toyota  Accord  2017    23744  10359  silver    IL
754  Nissan  Altima  2017    25716  10091     red    TX
181   Honda  Fusion  2018    72574  10032    blue    NY

[222 rows x 7 columns]

In [ ]:
df[(df["color"] =="white") | (df["state"] == "CA")][["make","model","price"]]

          make   model  price
0    Chevrolet   Cruze  37488
2    Chevrolet  Altima  40297
6         Ford   Camry  25049
9        Honda  Fusion  23514
10      Nissan   Cruze  15420
..         ...     ...    ...
986  Chevrolet  Accord  12039
987       Ford  Altima  44781
988     Toyota   Camry  45393
996  Chevrolet  Accord  15632
999  Chevrolet   Cruze  31827

[363 rows x 3 columns]

In [ ]:
df[(df["mileage"] < 70000) & (df["price"] < 800000)]

          make   model  year  mileage  price   color state
1       Toyota   Cruze  2017    19882  34176     red    IL
5       Toyota  Accord  2017    23744  10359  silver    IL
6         Ford   Camry  2012    39212  25049   white    TX
7        Honda   Cruze  2013    43679  41753     red    FL
8       Nissan  Fusion  2017    44843  14642     red    FL
..         ...     ...   ...      ...    ...     ...   ...
994  Chevrolet  Accord  2018    26933  21813  silver    TX
995      Honda  Altima  2017    25154  43139     red    FL
996  Chevrolet  Accord  2017    68264  15632   white    TX
997     Nissan   Cruze  2016    17417  30832  silver    IL
998      Honda  Accord  2011    68878  10801    blue    TX

[668 rows x 7 columns]

In [ ]:
df[df["year"] > 2018][["make", "model", "price"]]

          make   model  price
17      Nissan   Camry  46579
27      Nissan  Fusion  26857
51      Nissan   Camry  40150
55        Ford  Altima  36340
60       Honda   Cruze  47289
..         ...     ...    ...
982     Nissan  Fusion  10818
985       Ford  Fusion  48490
986  Chevrolet  Accord  12039
992      Honda  Accord  32248
994  Chevrolet  Accord  21813

[110 rows x 3 columns]

In [ ]:
df.sort_values("price", ascending= False).head(10)

          make   model  year  mileage  price   color state
635  Chevrolet  Accord  2011    14481  49998     red    FL
954     Nissan   Camry  2010    12725  49989     red    TX
275      Honda   Camry  2015    18206  49971  silver    CA
271      Honda  Fusion  2014    81328  49920     red    CA
277       Ford   Cruze  2017    68806  49907  silver    CA
962     Nissan   Camry  2010    13245  49884    blue    NY
554       Ford   Camry  2013    20731  49875  silver    IL
460     Toyota   Camry  2014    25844  49871     red    IL
248     Nissan  Altima  2012    17511  49787   black    NY
512     Nissan  Altima  2017    68580  49781    blue    FL

In [ ]:
#classify the cars
#<10000 then level1
#<25000 then level2
#<4000 then level3
#>4000 then level4
#create a new column price_status

# for i in df["price"]:
#   if i <10000:
#     print("level1")
#   elif i<25000:
#     print("level2")
#   elif i<=40000:
#     print("level3")
#   else:
#     print("level4")


def pricex(a):
  if a<10000:
    return "Level-1"
  elif a<=25000:
    return "Level-2"
  elif a<=40000:
    return "Level-3"
  else:
    return "Level-4"

df["Price_status"]=df["price"].map(pricex)

#df["Price_status"]= --> it will create the new column price_status
#df["price"].map(pricex) -> map function will map each and every value of price
#with the function of pricex

df.head()

,make,model,year,mileage,price,color,state,price_status,Price_status
0,Chevrolet,Cruze,2011,99157,37488,white,TX,Level-3,Level-3
1,Toyota,Cruze,2017,19882,34176,red,IL,Level-3,Level-3
2,Chevrolet,Altima,2011,77718,40297,blue,CA,Level-4,Level-4
3,Nissan,Fusion,2012,83613,43492,silver,TX,Level-4,Level-4
4,Ford,Cruze,2016,95349,26655,red,NY,Level-3,Level-3

In [ ]:
# Add a new column called car_category based on the following logic:

# If price is greater than or equal to 800000, label it as "Premium"

# If price is between 400000 and 799999, label it as "Mid-Range"

# If price is less than 400000, label it as "Budget"

# Use the existing price column to create this new column.

In [ ]:
def car_cat(b):
  if b >= 40000:
    return "Premium"
  elif b >= 20000:
    return "Mid-Range"
  else:
    return "Budget"

df["car_category"]=df["price"].map(car_cat)

In [ ]:
set(df["car_category"]) #set => remove duplicate

{'Budget', 'Mid-Range', 'Premium'}

In [ ]:
#Grouping
#it will group the columns

#group?
#boys => 4 (count) | 28 (Avg_Age)
#girls => 4 (count) | 25 (Avg_Age)

#aggregated functions => i will aggregate all the input data
#min / max / sum / count / average


print(df["price"].max())
print(df["price"].min())
print(df["price"].mean())
print(df["price"].count())

49998
10022
29376.222
1000

In [ ]:
df1 = df.groupby("make").agg(Total_count=("make","count"), Average_price=("price","mean"))

In [ ]:
df1.reset_index()

        make  Total_count  Average_price
0  Chevrolet          209   28676.253589
1       Ford          187   29929.144385
2      Honda          174   28687.770115
3     Nissan          224   29580.183036
4     Toyota          206   29944.184466

In [ ]:
#analyze my data and give Top 3 years that performed well

#in revenue (total_revenue - sum)
#in car count wise (total_car_count - count)
#in average price (average)

In [ ]:
df2 = df.groupby(["year"]).agg(Total_revenue=("price","sum"), Total_car_count=("make","count"), Average_price=("price","mean"))
df2.sort_values("Total_revenue", ascending= False).head(3).reset_index()[["year","Average_price"]]

   year  Average_price
0  2010   30356.519685
1  2011   28211.085938
2  2014   30180.610619

In [9]:
df1=df.groupby(["year"]).agg(Total_revenue=("price", "sum"),Total_car_count=("make","count"), Average_price=("price","mean"))
df2=df1.sort_values("Total_car_count",ascending=False).reset_index()
df2[["year","Total_car_count"]].head(3)

   year  Total_car_count
0  2011              128
1  2010              127
2  2013              114

In [10]:
df1=df.groupby(["year"]).agg(Total_revenue=("price", "sum"),Total_car_count=("make","count"), Average_price=("price","mean"))
df2=df1.sort_values("Average_price",ascending=False).reset_index()
df2[["year","Average_price"]].head(3)

   year  Average_price
0  2012   30388.252336
1  2010   30356.519685
2  2014   30180.610619